### ISSUE TITLE
test example failure; ValueError

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/pepatac#103]
I'm getting an error when running the [test example](https://github.com/databio/pepatac/tree/master/examples/test_project):

```
  File "/home/mjs5kd/code//pepatac/pipelines/pepatac.py", line 914, in post_dup_aligned_reads
    ar = float(pm.get_stat("Aligned_reads"))
ValueError: could not convert string to float: "b'18508\\n'"
```

It looks like the stats reporting might be off

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/3142784/PEPATAC_log.txt)

**Comment by michalstolarczyk** [comment]
oh, it worked when using `pypiper` on `dev`...

**Comment by michalstolarczyk** [comment]
failed later: https://github.com/databio/pepatac/issues/104

**Comment by nsheff** [comment]
I think I also already fixed this one as well. can you check with the dev branch after my recent PR?

**Comment by michalstolarczyk** [comment]
confirmed!
