### ISSUE TITLE
commands running on repeated pipeline run

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#107]
If you run the pipeline a second time immediately after running it once, ideally, there shouldn't be anything calculated. in PEPATAC though we're still re-calculating a bunch of stuff. Could these things better be done in follow functions?

These are things that are recalculated even after a pipeline is completed successfully:

> `samtools view -@ 4 -c -L /sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/SAMPLE/peak_calling_mm10/SAMPLE_peaks.narrowPeak /sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/SAMPLE/aligned_mm10/SAMPLE_sort_dedup.bam`

> `samtools idxstats /sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/SAMPLE/aligned_mm10/SAMPLE_temp.bam | gr
ep -we 'chrM' -we 'chrMT' -we 'M' -we 'MT' -we 'rCRSd'| cut -f 3`

Target to produce: `/sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/SAMPLE/aligned_mm10/SAMPLE_noMT.bam`

> `samtools idxstats /sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/SAMPLE/aligned_mm10/SAMPLE_sort.bam | cu
t -f 1 | grep -vwe 'chrM' -vwe 'chrMT' -vwe 'M' -vwe 'MT' -vwe 'rCRSd'| xargs samtools view -b -@ 8 /sfs/lustre/allocations/sheffla
b/processed/dura_macs/results_pipeline/SAMPLE/aligned_mm10/SAMPLE_sort.bam > /sfs/lustre/allocations/shefflab/processed/dura_macs/r
esults_pipeline/SAMPLE/aligned_mm10/SAMPLE_noMT.bam` (190761,190762,190763,190764)

**Comment by jpsmith5** [comment]
rerunning appears to be functioning correctly now (that is, not repeating unnecessary step)
