### ISSUE TITLE
streamline what reads files we keep

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#109]
Now the clean_add is working with the pypiper 0.11 update, so I'm wondering if we should revisit which files we keep... for exasmple, we're keeping `sorted.bam` and `dedup_sorted.bam`, plus files in the prealignments folder. I'm not sure we need all this...

**Comment by jpsmith5** [comment]
Some of these are now removed. Alternatively, the `--lite` option resolves the remainder.
