### ISSUE TITLE
Add option for abbreviated pipeline

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#11]
It could be useful to add an option such as --QC which would indicate that the pipeline is only being run to gain QC-level information. This would allow you to omit certain time-consuming steps (like making bigwigs etc) that arent necessary if you just need QC info.

**Comment by jpsmith5** [comment]
Is this an option that would still be of utility @rcorces?

Can you specify more so how you envision the checkpoint concept coming in to play here @nsheff?

**Comment by rcorces** [comment]
I'm not sure this is really necessary. If I followed the other thread correctly, some of the superfluous commands were removed and the extra time spent for QC is negligible.

**Comment by jpsmith5** [comment]
Agreed.  The majority of the runtime is consumed by the processes that would be "kept" in the abbreviated version.  Closing this for now.

**Comment by nsheff** [comment]
This may be of interest for a single-cell version, though... @cschmidl mentioned this to me as well.

for example, on a scATAC you wouldn't really need a smoothed bigwig track.

**Comment by rcorces** [comment]
This was the original thinking behind the abbreviated pipeline. We QC all of our libraries by MiSeq low depth sequencing at 200k reads per sample. So things like a smoothed bigwig track are not needed. I dont feel strongly. For scATAC, I imagine a lot of people will use pipelines from the companies (i.e. 10x Genomics CellRanger) so it may not be worth the investment on your end.

**Comment by nsheff** [comment]
I'm re-opening this so we can consider an abbreviated pipeline for scATAC.

@cschmidl said:

> For single cells I would skip the prealignments (HUGE), and get rid of the smoothened data (only take the "exact" folder), and also the non-deduplicated data I think

**Comment by jpsmith5** [comment]
I'll work on adding a sc-ATAC specific option.  I did end up adding a `--lite` option to essentially only keep the ultimate outputs along each branch, thereby saving significant disk space.

**Comment by nsheff** [comment]
We can also save space by zipping raw files, which we should definitely do (raised as separate issue #71)
