### ISSUE TITLE
singularity usage docs?

### ISSUE THREAD

**Issue by vreuter** [databio/pepatac#110]
I can't find usage docs for singularity. There's an extended tutorial with some information about installation, and there's a container usage page but that looks like it's tailored to docker. Is there usage info for singularity on the code.databio.org page?

**Comment by nsheff** [comment]
docs are incomplete for these links may help:

http://divvy.databio.org/en/latest/containers/
http://pepatac.databio.org/en/latest/howto/use-container/ (new version of docs for new pepatac that isn't quite ready yet)

**Comment by vreuter** [comment]
Thanks @nsheff -- those clarified things for me
