### ISSUE TITLE
Output BAMs have incomplete @RG line in header

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#112]
This may be beyond the scope of PEPATAC but the output BAM files cannot be directly used with certain tools (like GATK) because the header `@RG` line is incomplete. GATK requires (at least?) an SM and PL entry. The PEPATAC output bam looks like this:
`@RG     ID:ACCx-025FE5F8-885E-433D-9018-7AE322A92285-X034-S09-L133-B1-T1-P077`
And a complete `@RG` line would look something like this:
`@RG     ID:ACCx-025FE5F8-885E-433D-9018-7AE322A92285-X034-S09-L133-B1-T1-P077   SM:None LB:None PL:Illumina`

**Comment by jpsmith5** [comment]
Hey @rcorces, as follow up to this, do you then currently use something like picard's [`AddOrReplaceReadGroups`](http://broadinstitute.github.io/picard/command-line-overview.html#AddOrReplaceReadGroups) function? Or the [`samtools addreplacerg`](http://www.htslib.org/doc/samtools-1.5.html)?  `samtools` version can replace *all* `@RG` tags with a fixed string replacement, but not sure if that will be always desirable?

**Comment by rcorces** [comment]
I only needed to run one single sample through GATK so I just manually edited the header and moved on. I dont think the `@RG` tags of each read needs to be changed if that is what those tools do. It should just be the one line of the header that needs to have a little additional info (SM = sample, LB = Library, PL = platform). I dont remember how that info gets added to the header normally though.

**Comment by jpsmith5** [comment]
Gotcha, yeah I'm not immediately sure the source for the read group tags either.  May be a reflection of older read files versus those from newer tech? Were the originating reads for your case from an older sequencing platform at all?

**Comment by rcorces** [comment]
Just did some googling on this. I think you just need to pass a few extra command line options to bowtie2 (according to this post http://seqanswers.com/forums/showthread.php?t=28100). Though that post is a bit out of date.
From the samtools manual, the correct command line option would be `--rg` and this is how you would add the SM, LB, and PL info to the header:
![image](https://user-images.githubusercontent.com/10343046/60531797-9afd9d00-9cb0-11e9-827a-76e0774c0e42.png)

All that being said, I'm not sure how you would determine the platform used for sequencing at run time nor what values you would want to use for the SM and LB annotations. You could either make these meaningful or just use `None` to make sure that the files at least have the correct header format for GATK. But using `None` seems less elegant and I dont know enough about these SAM tags to know what they are used for by other tools.

**Comment by jpsmith5** [comment]
Closing this for now, but you can [read a post from GATK for information regarding read group headers](https://gatk.broadinstitute.org/hc/en-us/articles/360035532352) for GATK.
