### ISSUE TITLE
MACS2 customization 

### ISSUE THREAD

**Issue by sthair** [databio/pepatac#113]
Hi there, I would like to run PEPATAC using MACs and also set the MACs settings to match this statement
```Peak calling was performed by MACS2 narrow peak mode with parameters –q 0.01 –nomodel –shift 0```

Can I just add the parameters to my command like this: 
```singularity exec --bind ${GENOMES} --bind /labs/syang5 --bind ${ANNOTATIONS} --bind ${PEPATAC} $PEPATAC/pepatac ${PEPATAC}/pipelines/pepatac.py --single-or-paired paired --prealignments rCRSd human_repeats --peak-caller macs2 –q 0.01 –nomodel –shift 0 --genome hg38 --sample-name test1 --input examples/data/test1_r1.fastq.gz --input2 examples/data/test1_r2.fastq.gz --genome-size hs -O $HOME/pepatac_test```
?
thanks!

**Comment by vreuter** [comment]
Hi @sthair the settings that you mention for `macs2` should be the defaults, but you can use the `pepatac.yaml` config file to change settings for `macs2` and other tools that `pepatac` uses.

**Comment by sthair** [comment]
Hi thank you so much! 
Can you explain a little further, I don't like to edit source files. 
so eg I would edit the .yaml and ideally save as pepatac_stedit.yaml
but then how do I make sure it uses the new yaml?
S

**Comment by sthair** [comment]
so I tried editing the .yaml file and then ran this: 
```singularity exec --bind ${GENOMES} --bind /labs/syang5 --bind ${ANNOTATIONS} --bind ${PEPATAC} $PEPATAC/pepatac ${PEPATAC}/pipelines/pepatac.py -P 8 -C pepatac_st1.yaml --single-or-paired paired --prealignments rCRSd human_repeats --genome hg19 --sample-name D4_LPStest_hg19 --input examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R1_001.fastq.gz --input2 examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R2_001.fastq.gz --genome-size hs -O $HOME/pepatac_D4hg19newmacs``` but that failed. ```Changed status from initializing to running.
#No config file
#Traceback (most recent call last):
 # File "/scg/apps/software/pepatac/0.8.6/pepatac/pipelines/pepatac.py", line 1422, in <module>
  #  sys.exit(main())
  #File "/scg/apps/software/pepatac/0.8.6/pepatac/pipelines/pepatac.py", line 476, in main
   # tools = pm.config.tools``` any help to get this running much appreciated. @vreuter

**Comment by sthair** [comment]
Hello @vreuter @nsheff   so I have tried a lot of different tweaked versions but basically I got it running without singularity and the command is like this ```python pipelines/pepatac.py -P 8 --single-or-paired paired --prealignments rCRSd human_repeats --genome hg19 --sample-name D4_LPS_testnosing --input examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R1_001.fastq.gz --input2 examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R2_001.fastq.gz --genome-size hs -O $HOME/pepatac_D4_testnosing```. works. 

then I added my modified .yaml file to the pipeline directory and ran this according to the usage ```python pipelines/pepatac.py --config pipelines/pepatac_st1.yaml -P 8 --single-or-paired paired --prealignments rCRSd human_repeats --genome hg19 --sample-name D4_LPS_testnosing2 --input examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R1_001.fastq.gz --input2 examples/data/D4-LPS-1-TAAGGCGA-GCGATCTA_S1_L003_R2_001.fastq.gz --genome-size hs -O $HOME/pepatac_D4_testnosing2``` fails. 

error message: Changed status from initializing to running.
No config file
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1422, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 476, in main
    tools = pm.config.tools
AttributeError: 'NoneType' object has no attribute 'tools'
Pipeline status: running

### Pipeline failed at:  (06-03 18:19:48) elapsed: 2.0 _TIME_

Total time: 0:00:03

help?

**Comment by sthair** [comment]
ps the only thing I changed in the pepatac.yaml is that macs2 is now -q 0.1

**Comment by nsheff** [comment]
can you provide the entire log file? Also, please confirm -- from the directory you are running the `python ...` command, can you type `ls pipelines/pepatac_st1.yaml` and  confirm it's in that relative location? 

and does it work if you *don't* rename it, but just edit the existing `pepatac.yaml` file and then *not* specify with `--config` ?

**Comment by sthair** [comment]
Hi thank you! 
OK 
1. ```[sthair@smsx10srw-srcf-d15-35 pepatac]$ pwd
/home/sthair/pepatac
[sthair@smsx10srw-srcf-d15-35 pepatac]$ ls pipelines/pepatac_st1.yaml
pipelines/pepatac_st1.yaml
[sthair@smsx10srw-srcf-d15-35 pepatac]$ ls pipelines/
pepatac_backup.yaml  pepatac.py  pepatac_st1.yaml  pepatac.yaml
[sthair@smsx10srw-srcf-d15-35 pepatac]$ 
```
2. 
[pepatac_D4_testnosing2_log.txt](https://github.com/databio/pepatac/files/3250256/pepatac_D4_testnosing2_log.txt)

3. Editing the yaml directly and trying again now..

**Comment by sthair** [comment]
PS. I am not super strong in python so this could be way off but I noticed that in pepatac.py ```def parse_arguments()``` there is no ```parser.add_argument``` defined for --config

**Comment by nsheff** [comment]
the config param is added by the `add_pypiper_args` since it's shared across pipelines. you can see it's getting correctly recieved by the pipeline: 

```
*        `config_file`:  `pipelines/pepatac_st1.yaml`
```

the config file is assumed to relative to the pipeline script, rather than to the current working directory. sorry for the confusion -- just take of 'pipelines/' here.

so: `--config pepatac_st1.yaml` will work.

**Comment by sthair** [comment]
HI, thank you! 

That helps a lot. So "relative to the pipeline script" means that if it is in the same directory as the pipeline script, then I don't provide the path. 

Also FYI, point 3 above worked when I just edit the original .yaml file, but I am missing some QC files so I am working with the server master as per my other run on sentence in the other issue I have posted, I think I am not completely contained in my home directory. 
Really appreciate your assistance here. 
Will update later on

**Comment by sthair** [comment]
Have everything pointing at the correct directories and this works now thanks!
