### ISSUE TITLE
Insert size distribution

### ISSUE THREAD

**Issue by sthair** [databio/pepatac#114]
Hi there, 
I ran pepatac on an old sample that was processed with the Chang pipeline at Stanford. 

The insert size distribution shape looks exactly the same but the magnitude is 10X less. Is this the data subsetted for the graph? Or is it subsetted completely? This runs extremely fast and I got back way less peaks than expected as well.... 

If it is subsetted, can I change it to run everything? This is neutrophil data so largely closed chromatin.. 

[D4_new.pdf](https://github.com/databio/pepatac/files/3248873/D4_new.pdf) *pepatac
[D4_old.pdf](https://github.com/databio/pepatac/files/3248874/D4_old.pdf) *changpipe

thanks!
Simone

**Comment by jpsmith5** [comment]
To my understanding, no, this should not be subset in any way.  The fragment count is simply being determined from the aligned and sorted bam file (minus duplicates), and the number of unique fragment sizes tallied.  I don't believe this has been changed from early versions of the pipeline so I am equally confused why you're seeing such a decrease in read count.  You could look at the two BAM files (if you have the original?) and check how many properly paired, aligned reads are in each?

Optionally, you can modify the MACS2 parameters in a custom config file or just modify the pipelines/pepatac.yaml file directly to adjust those settings if you feel like you'd want less restrictive peak calling parameters. I'll keep looking into the fragment size distribution.

**Comment by nsheff** [comment]
can you send us the log files from each run?

**Comment by sthair** [comment]
Thank you so much! So I am sorting out a few things on my end with the server master, we got it working but he helped a lot the first time around and we were running it with singularity as we are not allowed to use docker and I am totally new to that concept and all of the usage that goes with it. ... and turns out the directories it points to I do not have permission to edit the yaml. The copy of the pipe I have in my local directory does run now with just basic command line usage.  when I edit the yaml  it runs but I am now missing QC files(this is more along the lines of my other issue posted)...

 I think because something in the main .py script has been modified to still point to directories outside of my home. Once I know that what I think I am doing, I am actually doing, I will go back and check these points and send those logs as I hope they will be a lot less of a mess. Unfortunately I am really not well versed in the structure of shared servers/ clusters and so it is confusing to me and the server master has me and everyone else to deal with at the same time.
