### ISSUE TITLE
Merge bam files for duplicates prior to calling peaks

### ISSUE THREAD

**Issue by sthair** [databio/pepatac#117]
Hi there, 
I am wondering if there is a way to merge the _sort_dedup.bam files for duplicate samples, assign to rmdup_bam, and then call peaks/ run the rest of the pipe from that. These are paired end samples FYI
thanks!
Simone

**Comment by nsheff** [comment]
is there a reason you want the earlier steps run separately? If not you can use this: 

https://pepkit.github.io/docs/sample_subannotation/

it will merge them at the beginning, though.
