### ISSUE TITLE
bamSitesToWig asking for non-integer number of cores

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#119]
After a recent update, I'm getting an error with bamSitesToWig where it calls for a non-integer number of cores via the `-p` argument:
`bamSitesToWig.py: error: argument -p/--cores: invalid int value: '5.333333333333333'`

This comes from this line which introduces a divide by 3 outside of the `int()` call:
https://github.com/databio/pepatac/blob/a0e4347b199c91bbfd7d994b0705da2ca8d51015/pipelines/pepatac.py#L1036

I was looking back through the git history on this and it looks like a collision of two commits around the same time caused this problem? It looks like this commit had fixed the problem on 3/22: https://github.com/databio/pepatac/commit/2d6e6e17d3db657a7406347496550f389d02c36d

but somehow that commit seems to have gotten unintentionally overwritten by this commit on 3/25:
https://github.com/databio/pepatac/commit/2a459539907ca09f9f4514bbf44e64110c7853f1

The difference is the placement of the `int()`

Log attached but I think I've properly diagnosed the problem?

[PEPATAC_log.md.txt](https://github.com/databio/pepatac/files/3346591/PEPATAC_log.md.txt)

**Comment by nsheff** [comment]
Yep. I think you're exactly right. in the meantime if you use a number of cores that's divisible by 3 it should go away :).

**Comment by nsheff** [comment]
@jpsmith5 do you want to correct this?

**Comment by jpsmith5** [comment]
It was re-corrected already.  Trying to finish up testing dev branch before merging into master, then it'll be corrected there again.

**Comment by jpsmith5** [comment]
No longer an issue
