### ISSUE TITLE
Make bowtie2 parameterizable

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#12]
Right now there are several sets of bowtie2 parameters, eg, those used for prealignments, vs for genome alignment.

These are currently hard-coded, but should be moved to the pipeline config file so people can change them if they want.

**Comment by jpsmith5** [comment]
@nsheff -- The pipeline does handle SE data at this point.  Is there still interest in parameterizing `bowtie2` from the user perspective?

**Comment by nsheff** [comment]
let's make 2 'command parameter' chunk options for the `pepatac.yaml` pipeline config file, one for prealignments and one for primary alignment.

**Comment by nsheff** [comment]
@jpsmith5 this is related to #87, can you solve them both

**Comment by jpsmith5** [comment]
Addressed with 4ce8666
