### ISSUE TITLE
Siphoning off Alu repeats

### ISSUE THREAD

**Issue by juheon** [databio/pepatac#121]
Could you explain why do you use prealignment to siphon off Alu repeats?
The elimination of rRNA DNA and alpha satellites makes sense to me, assuming I am interested in the non-centromere genomic regions and non-rRNA DNA regions. However, Alu sequences are abundant (~10% of the human genome) and often overlap with GENCODE TSS location. I think prealignment of Alu repeats may result in false-negative ATAC peaks at TSS locations. Maybe, I am missing some biological rationales for the prealignment step. Could you describe what was the rationale of the elimination of Alu repeats?

**Comment by nsheff** [comment]
Sorry I missed this issue earlier.

If those sequences are present in the genome many times, then you won't be able to reliably align them anyway. If you require unique alignments they will show up as unmapped reads; if you allow multimapping you'll randomly assign them and they won't be much use anyway. If I recall correctly, in my hands, aligning to Alu eliminated some artifacts. 

But it's easy to turn off; just remove that from the prealignment list. You could try it both ways easily using a subproject and see what it changes.
