### ISSUE TITLE
ModuleNotFoundError: No module named 'pypiper'

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [databio/pepatac#122]
Hi
I am now test this PEPATAC pipline.I install pypiper python package by miniconda3,but when I test the pepatac.py without looper it shows No module named 'pypiper'.Could anyone help me with the error?Thanks so much in advance.

**Comment by nsheff** [comment]
What command did you use to install?

On pypi, the pypiper package is called `piper` (not `pypiper`).

**Comment by qiaowei-vvjoe** [comment]
@nsheff 
Hi
I am so sorry for that stupid question but I just test the pepatac.py.

python3 pepatac.py -P 5 -O /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/example/data -S test_without_looper -G hg38  -Q paired  -C pepatac.yaml  -gs hs -I /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz -I2 /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz

**Comment by nsheff** [comment]
Hi, you're not *installing pypiper* correctly. this shows how to install it: 

http://pypiper.databio.org/en/latest/

**Comment by qiaowei-vvjoe** [comment]
Hi @nsheff
I just wget https://github.com/databio/pypiper/archive/v0.12.0.zip
then unzip v0.12.0.zip
then go to pypiper-0.12.0/example_pipelines 
to test python3 hello_pypiper.py

but it still showed No module named 'pypiper'
did I do any wrong steps?
I am so sorry for that stupid question.

**Comment by nsheff** [comment]
you have not installed pypiper. please install pypiper first. please read my earlier comments.

**Comment by qiaowei-vvjoe** [comment]
@nsheff 
Hi Nathan
I have installed pypiper according to your comment and  run python3 hello_pypiper.py successfully.
### Pipeline completed. Epilogue
*        Elapsed time (this run):  0:00:01
*  Total elapsed time (all runs):  0:00:00
*         Peak memory (this run):  0 GB
*        Pipeline completed time: 2019-08-17 10:03:27

But when I test the example there comes other errors, for me now I just know the line36. The examples/data/test1 is come from the PEPATAC. Could you please give me a help for this problem?I am so sorry for these too much questions.Thank you so much.

$ python3 pepatac.py -P 5 -O /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/examples/data -S test1_without_looper -G hg38  -Q paired  -C pepatac.yaml  -gs hs -I /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz -I2 /mnt/disk1/qiaowei/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz

Traceback (most recent call last):
  File "pepatac.py", line 1422, in <module>
    sys.exit(main())
  File "pepatac.py", line 461, in main
    args = parse_arguments()
  File "pepatac.py", line 36, in parse_arguments
    required=["input", "genome", "sample-name", "output-parent"])
  File "/mnt/disk1/qiaowei/miniconda3/lib/python3.7/site-packages/pypiper/utils.py", line 60, in add_pypiper_args
    argument_groups=groups, arguments=args, use_all_args=all_args)
  File "/mnt/disk1/qiaowei/miniconda3/lib/python3.7/site-packages/pypiper/utils.py", line 808, in _determine_args
    from logmuse import LOGGING_CLI_OPTDATA
ImportError: cannot import name 'LOGGING_CLI_OPTDATA' from 'logmuse' (/mnt/disk1/qiaowei/miniconda3/lib/python3.7/site-packages/logmuse/__init__.py)

**Comment by jpsmith5** [comment]
Did you have any more luck with this @qiaowei-vvjoe? I can run your command, modified for my file system successfully.

From the pepatac parent folder:
```
python3 pipelines/pepatac.py -P 5 -O /project/shefflab/pepatac_tutorial/data -S test1_without_looper -G hg38 -Q paired -C $CODE/pepatac/pipelines/pepatac.yaml -gs hs -I $CODE/pepatac/examples/data/test1_r1.fastq.gz -I2 $CODE/pepatac/examples/data/test1_r2.fastq.gz
```

Which version of the pipeline were you attempting here? Most recent version should be 0.9.5.

**Comment by jpsmith5** [comment]
If you have another issue in this line of questioning please let us know @qiaowei-vvjoe

**Comment by qiaowei-vvjoe** [comment]
I am very sorry that I have left the place where I worked last year without solving this problem , but still thank you very much for your help.I will test it again according to your command.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "databio/pepatac"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 凌晨3:03
收件人:&nbsp;"databio/pepatac"<pepatac@noreply.github.com&gt;;
抄送:&nbsp;"乔玮"<1270885824@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [databio/pepatac] ModuleNotFoundError: No module named 'pypiper' (#122)





 
Did you have any more luck with this @qiaowei-vvjoe? I can run your command, modified for my file system successfully.
 
From the pepatac parent folder:
 python3 pipelines/pepatac.py -P 5 -O /project/shefflab/pepatac_tutorial/data -S test1_without_looper -G hg38 -Q paired -C $CODE/pepatac/pipelines/pepatac.yaml -gs hs -I $CODE/pepatac/examples/data/test1_r1.fastq.gz -I2 $CODE/pepatac/examples/data/test1_r2.fastq.gz  
Which version of the pipeline were you attempting here? Most recent version should be 0.9.5.
