### ISSUE TITLE
TypeError: descriptor 'splitlines' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by mbardus** [databio/pepatac#126]
When I run the pepatac on the test example I get this error in pepatac.py:

TypeError: descriptor 'splitlines' requires a 'str' object but received a 'unicode'

in this line:

ftList = str.splitlines(ftList)

it works if I change into:

ftList = unicode.splitlines(ftList)

**Comment by nsheff** [comment]
I believe this is a python2 error. See also https://github.com/databio/pepatac/issues/116#issuecomment-503319578

Fixed in PR #118.

**Comment by nsheff** [comment]
This is now fixed in master.
