### ISSUE TITLE
Missing refgenie assets

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#128]
On dev I get this error:

```
The 'blacklist' asset does not exist.
Update your REFGENIE config file to include this asset, or point directly to the file using --blacklist.

The 'tss_annotation' asset does not exist.
Update your REFGENIE config file to include this asset, or point directly to the file using --TSS-name.
```

What's the status of these assets?

**Comment by jpsmith5** [comment]
TSS annotation is fixed to use the proper `refgenie` asset. 

Blacklist lives as an optional item at the moment, but it probably could become another `refgenie` managed asset. Would just be a downloaded file that then get's managed by it.

Will add it to `refgenie`.

**Comment by jpsmith5** [comment]
Blacklist is now a live recipe in dev; see https://github.com/databio/refgenie/commit/7d54d0bb6bd6460b9bf251a91c99855964b842f2

**Comment by nsheff** [comment]
also must make sure it's on refgenomes.databio.org though.

**Comment by jpsmith5** [comment]
Ah. Yes. Will do.

**Comment by stolarczyk** [comment]
done: http://refgenomes.databio.org/v2/asset/hg38/blacklist/splash?tag=default
