### ISSUE TITLE
alignment repeats

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#132]
This command is repeating every time I run the pipeline:

```
### Map to human_rDNA (03-05 08:26:20) elapsed: 0.0 _TIME_

Target to produce: `/project/shefflab/processed/paqc/results_pipeline/GSM4289908/prealignments/GSM4289908_human_rDNA_unmap.fq.gz`  

> `(bowtie2 -p 4 -k 1 -D 20 -R 3 -N 1 -L 20 -i S,1,0.50 -x /project/shefflab/genomes/human_rDNA/bowtie2_index/default/human_rDNA --rg-id GSM4289908 -U /project/shefflab/processed/paqc/results_pipeline/GSM4289908/fastq/GSM4289908_R1_trim.fastq --un /project/shefflab/processed/paqc/results_pipeline/GSM4289908/prealignments/GSM4289908_human_rDNA_unmap.fq > /dev/null) 2>/project/shefflab/processed/paqc/results_pipeline/GSM4289908/prealignments/GSM4289908_human_rDNA_bt_aln_summary.log` (159924)
<pre>
```

It is **not recognizing that the target should be already completed**. It should skip the step if it's already been run.

**Comment by jpsmith5** [comment]
The target unmap file should be getting compressed following alignment.  If it fails that step, it will then always be rerunning this step.  Couldn't compress before because subsequent prealignments would need to uncompress first each time.  Can confirm c49c734 resolves it before attempting anything else.

**Comment by nsheff** [comment]
In that case, those should be tied into one `run` call shouldn't they?

**Comment by jpsmith5** [comment]
Tthe prealignment is a separate function that returns the unmap files. It loops through all prealignments. Then it compresses.  If you compress within the prealignment function, it would have to uncompress as it looped through all prealignments.

**Comment by nsheff** [comment]
I'm lost, sorry.

**Comment by jpsmith5** [comment]
Working as intentded for now, but could be improved in relation to handling of compressed versus uncompressed target files.  See thoughts at databio/pypiper#171.
