### ISSUE TITLE
macs2 error

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#134]
the first paqc sample yields this error:

```
### Call peaks (03-06 09:29:06) elapsed: 40.0 _TIME_

Target to produce: `/project/shefflab/processed/paqc/results_pipeline/GSM4289908/peak_calling_hg38/GSM4289908_peaks.narrowPeak`  

> `macs2 callpeak -t /project/shefflab/processed/paqc/results_pipeline/GSM4289908/aligned_hg38_exact/GSM4289908_shift.bed --outdir /project/shefflab/processed/paqc/results_pipeline/GSM4289908/peak_calling_hg38 -n GSM4289908 -g hs -f BED -q 0.01 --shift 0 --nomodel` (145879)
<pre>
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 652, in <module>
    main()
  File "/usr/local/bin/macs2", line 49, in main
    from MACS2.callpeak_cmd import run
  File "/usr/local/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/usr/local/lib/python3.7/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 918, in init MACS2.IO.Parser
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
</pre>
Command completed. Elapsed time: 0:00:03. Running peak memory: 5.424GB.  
  PID: 145879;	Command: macs2;	Return code: 1;	Memory used: 0.022GB

Starting cleanup: 8 files; 3 conditional files for cleanup
```

not sure if this is a macs2 problem or what..,.

this is using a singularity container

**Comment by nsheff** [comment]
I tried rebuilding the container, but it didn't work. 

we are using the latest biocontainer.

**Comment by jpsmith5** [comment]
I just ran the test sample through with the `--strict` option and it used MACS2 from the container without issue.

Have to update the bulker manifest to do so as follows:
```
  imports:
  - bulker/alpine:default
  host_commands:
  - awk
  - cat
  - cut
  - date
  - grep
  - hostname
  - java
  - ln
  - mkfifo
  - mv
  - perl
  - python
  - sed
  - sh
  - sort
  - tee
  - uniq
  - wc 
  - xargs
```

I also create a python virtualenv first before running everything through:
```
virtualenv -p /usr/bin/python3 pepatac_bulker
source pepatac_bulker/bin/activate
```

Install required python (sans MACS2)
```
pip install loopercli \
numpy \
pararead \
pandas \
piper \
refgenconf \
refgenie \
```

Load and activate bulker
```
bulker load pepatac -f /home/jps3dp/src/hub.bulker.io/databio/pepatac.yaml --strict
bulker activate pepatac -f /home/jps3dp/src/hub.bulker.io/databio/pepatac.yaml --strict
```

Run the tutorial sample
```
looper run examples/tutorial/tutorial.yaml --compute local
```

**Comment by jpsmith5** [comment]
Tested again with most recent crate and bulker updates with this sample and no issues. Can reopen if similar issue arises in the future.

**Comment by bioarpit1** [comment]
Trying to follow the tutorial to run from singularity container macs2 missing error is coming. I am using latest docker image to build the singularity container (latest image was pushed 3 month back)
*              Command:  `/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py --single-or-paired paired --prealignment-index rCRSd= /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/rCRSd/bowtie2_index/default/rCRSd. --genome hg38 --genome-index /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/bowtie2_index/default/hg38. --chrom-sizes /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/fasta/default/hg38.chrom.sizes --sample-name test1 --input /home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz --input2 /home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz --genome-siz hs -O /home/amishra/pepatac_tutorial/`
*         Compute host:  SRV-SINGLE-01.BRIVMRC.ORG
*          Working dir:  /home/amishra
*            Outfolder:  /home/amishra/pepatac_tutorial/test1/
*  Pipeline started at:   (03-04 23:54:57) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.10.6
*          Pypiper dir:  `/usr/local/lib/python3.10/dist-packages/pypiper`
*      Pypiper version:  0.12.3
*         Pipeline dir:  `/home/amishra/pepatac_tutorial/tools/pepatac/pipelines`
*     Pipeline version:  0.10.4
*        Pipeline hash:  756632d1bd9aae182eab10e34b294f08744663cc
*      Pipeline branch:  * master
*        Pipeline date:  2023-02-22 10:19:16 -0500
*        Pipeline diff:  2 files changed, 2 insertions(+), 2 deletions(-)

### Arguments passed to pipeline:

*           `TSS_name`:  `None`
*            `aligner`:  `bowtie2`
*          `anno_name`:  `None`
*          `blacklist`:  `None`
*        `chrom_sizes`:  `/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/fasta/default/hg38.chrom.sizes`
*        `config_file`:  `pepatac.yaml`
*              `cores`:  `1`
*       `deduplicator`:  `samblaster`
*              `dirty`:  `False`
*             `extend`:  `250`
*              `fasta`:  `None`
*       `force_follow`:  `False`
*     `frip_ref_peaks`:  `None`
*    `genome_assembly`:  `hg38`
*       `genome_index`:  `/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/bowtie2_index/default/hg38.`
*        `genome_size`:  `hs`
*              `input`:  `['/home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz']`
*             `input2`:  `['/home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz']`
*               `keep`:  `False`
*               `lite`:  `False`
*             `logdev`:  `False`
*                `mem`:  `4000`
*              `motif`:  `False`
*          `new_start`:  `False`
*            `no_fifo`:  `False`
*           `no_scale`:  `False`
*      `output_parent`:  `/home/amishra/pepatac_tutorial/`
*         `paired_end`:  `True`
*        `peak_caller`:  `macs2`
*          `peak_type`:  `fixed`
* `prealignment_index`:  `['rCRSd=', '/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/rCRSd/bowtie2_index/default/rCRSd.']`
* `prealignment_names`:  `[]`
*         `prioritize`:  `False`
*            `recover`:  `False`
*        `sample_name`:  `test1`
*        `search_file`:  `None`
*             `silent`:  `False`
*   `single_or_paired`:  `paired`
*             `skipqc`:  `False`
*                `sob`:  `False`
*           `testmode`:  `False`
*            `trimmer`:  `skewer`
*          `verbosity`:  `None`

----------------------------------------

The following required tool(s) are not callable: macs2




### Pipeline failed at:  (03-04 23:54:57) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Missing required tools. See message above.
Traceback (most recent call last):
  File "/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 2779, in <module>
    sys.exit(main())
  File "/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 602, in main
    pm.fail_pipeline(RuntimeError(err_msg))
  File "/usr/local/lib/python3.10/dist-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
RuntimeError: Missing required tools. See message above.
