### ISSUE TITLE
Alignment fails if no prealignments are specified

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#138]
Here, I specified no pre-alignments.

Is it possible there's some zip/unzip step that is basically assuming you have at least 2 prealignment?

### Prealignments (04-20 16:39:28) elapsed: 134.0 _TIME_

You may use `--prealignments` to align to references before the genome alignment step. See docs.

### Map to genome (04-20 16:39:28) elapsed: 0.0 _TIME_

Target to produce: `/project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/aligned_hg38/GSM4467115_sort.bam`  

> `bowtie2 -p 8  --very-sensitive -X 2000 --rg-id GSM4467115 -x /project/shefflab/genomes/hg38/bowtie2_index/default/hg38 -1 /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/GSM4467115_R1_trim.fastq.gz -2 /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/GSM4467115_R2_trim.fastq.gz | samtools view -bS - -@ 1  | samtools sort - -@ 1 -T /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/aligned_hg38/tmpgz7n5w2g -o /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/aligned_hg38/GSM4467115_temp.bam` (220611,220612,220613)
<pre>
WARNING: Bind mount '/home/ns5bc => /home/ns5bc' overlaps container CWD /home/ns5bc/code/atac_ebna2, may not be available
WARNING: Bind mount '/home/ns5bc => /home/ns5bc' overlaps container CWD /home/ns5bc/code/atac_ebna2, may not be available
WARNING: Bind mount '/home/ns5bc => /home/ns5bc' overlaps container CWD /home/ns5bc/code/atac_ebna2, may not be available
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /opt/singularity/3.5.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
WARNING: Skipping mount /opt/singularity/3.5.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
WARNING: Skipping mount /opt/singularity/3.5.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
stat: Bad file descriptor
Warning: Could not open read file "/project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/GSM4467115_R1_trim.fastq.gz" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
</pre>
Command completed. Elapsed time: 0:00:01. Running peak memory: 0.274GB.  
  PID: 220611;	Command: bowtie2;	Return code: 1;	Memory used: 0.018GB  
  PID: 220613;	Command: samtools;	Return code: 0;	Memory used: 0.016GB  
  PID: 220612;	Command: samtools;	Return code: 0;	Memory used: 0.002GB

Starting cleanup: 1 files; 3 conditional files for cleanup

Cleaning up flagged intermediate files. . .

Conditional flag found: []

These conditional files were left in place:

- /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/GSM4467115*.fastq
- /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/*.fastq
- /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/fastq/*.log
- /project/shefflab/processed/atac_ebna2/results_pipeline/GSM4467115/aligned_hg38/tmpgz7n5w2g

### Pipeline failed at:  (04-20 16:39:29) elapsed: 1.0 _TIME_

Total time: 0:02:46
Failure reason: Subprocess returned nonzero result. Check above output for details
Traceback (most recent call last):
  File "/home/ns5bc/code/pepatac/pipelines/pepatac.py", line 2211, in <module>
    sys.exit(main())
  File "/home/ns5bc/code/pepatac/pipelines/pepatac.py", line 884, in main
    follow=check_alignment_genome)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 777, in run
    self.callprint(cmd_i, shell, lock_file, nofail, container)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 1028, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 2131, in _triage_error
    self.fail_pipeline(e)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details

**Comment by nsheff** [comment]
btw, the same command worked when I specified a single pre-alignment.

**Comment by jpsmith5** [comment]
Fixed with 10e75d1
