### ISSUE TITLE
invalid Project.looper.output_dir reference

### ISSUE THREAD

**Issue by stolarczyk** [databio/pepatac#139]
https://github.com/databio/pepatac/blob/c18f50e6644cb5b116f982d1a61aa86dd0dbe239/PEPATACr/R/PEPATACr.R#L2341

After recent looper change, where we moved _required_ `Project.looper.output_dir` attribute, lines like the one above are no longer valid.

Currently, looper user can set the output directory via:
 - `Project.looper.all.output_dir` or `Project.looper.all.output-dir`
 - `Project.looper.<command>.output_dir` or `Project.looper.<command>.output-dir`
 - CLI (no `output_dir` info in the PEP at all)

Therefore we can no longer rely on `output_dir` being available as the `Project` object attr

**Comment by stolarczyk** [comment]
best solution I can come up with is adding the output_dir to the looper namespace and simply use it in the command template to pass it to the summarizer script.

But, currently we have:
 - output_folder -- parent output folder provided in project.looper.output_folder
 - sample_output_folder -- A sample-specific output folder ({output_folder}/{sample_name})

so adding output_dir will be confusing, we'd need to rename things

**Comment by jpsmith5** [comment]
Yeah that's challenging. Since project level runs were always in the same directory previously this logic made sense, but now that the project output could be in a different location I may need to rethink the whole process. It still has to know the location of all sample output, maybe instead I derive a project level output from sample level output by stripping directories?

**Comment by nsheff** [comment]
can this be closed now? we should use `looper.results_subdir`, right?

wait, how is this different from `looper.sample_output_folder` ?

**Comment by stolarczyk** [comment]
https://github.com/pepkit/looper/blob/dev/docs/variable-namespaces.md#4-looper

looper.sample_output_folder = looper.results_subdir/sample.sample_name

**Comment by nsheff** [comment]
duh! got it! sorry, mental lapse... so @jpsmith5 are we good to close this?

- `output_dir` -- parent output directory provided in `project.looper.output_dir` in the project configuration file
- `results_subdir` -- the path to the results directory. It is a sub direcotry of `output_dir` called `project.looper.results_subdir` or "results_pipeline" by default
- `sample_output_folder` -- A sample-specific output folder (`results_subdir`/`sample.sample_name`)

**Comment by jpsmith5** [comment]
Should be resolved. Closing for now.
