### ISSUE TITLE
README structure suggestion

### ISSUE THREAD

**Issue by carbonwei** [databio/pepatac#14]
0.add an content.
1.current 'Pipeline features at-a-glance'.
2.Installation, including current 'Installing' and 'Configuring'.
3.Usage, including 
(1) current 'Running the pipeline'.
(2) to-be-added usage of parameters, which can include current 'Outline of analysis steps'.
(3) examples of both looper-based and through commend line.
(4) current 'Using a cluster' for cluster usage setup
4.Output structure

N-1.Contributing
N.Contributors

**Comment by jpsmith5** [comment]
This information has been shifted to website docs.  Closing for now.
