### ISSUE TITLE
File not found during bowtie2 step

### ISSUE THREAD

**Issue by hugokitano** [databio/pepatac#142]
I ran pepatac on mouse bulk atac seq for the first time, and I'm running into an issue where a file is not found in an intermediate step. 

```
Warning: Could not open read file "/oak/stanford/groups/satpathy/users/hkitano/atacseq/atacseq_ctr_r1/fastq/atacseq_ctr_r1_R1_trim.fastq.gz" for reading; skipping...
Error: No input read files were valid
```
I took a look in this directory, and saw that the trimmed fastq does exist, but it is not gzipped.
![image](https://user-images.githubusercontent.com/8139124/87254724-6b43b200-c439-11ea-85d2-a1fc66d16ac7.png)

My log is attached. Thank you!

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/4909267/PEPATAC_log.txt)

**Comment by jpsmith5** [comment]
Hi @hugokitano . Found what I believe is the issue. Give the updated version a try. It should resolve your error.  If not, let us know and I'll dive back in. Thanks for working with us!

**Comment by jpsmith5** [comment]
Presumably this is resolved as expected. Closing for now.
