### ISSUE TITLE
Bigwig track normalized or not?

### ISSUE THREAD

**Issue by Zhuxitong** [databio/pepatac#144]
Hi, 

The nice tools PEPATAC can produce BigWig signal tracks: nucleotide-resolution ("exact cut") signal and smoothed signal. I believe the smoothed signal will be more proprely to view in Genome broswer like IGV. However, do these tracks including the raw read depth or normalized signal? I mean if we can directly compare the tracks in IGV from different samples?

Any suggestions would be very grateful!

**Comment by jpsmith5** [comment]
Hey @Zhuxitong, with the last 2 releases it *does* normalize by read count by default.  This can be stopped with the `--no-scale` option, which would produce the raw read version.  Alternatively, if you use seqOutBias, `--sob`, it scales by the expected/observed cut frequency based on the mappability of the genome using a kmer of the length of the reads.  To use seqOutBias then, you'd need to have [already generated the appropriate `refgenie` assets](https://github.com/databio/pepatac/blob/master/docs/sob.md) for the read length of your samples.

**Comment by Zhuxitong** [comment]
Thanks @jpsmith5 I will feel comfortable to compare my samples :)

**Comment by jpsmith5** [comment]
Welcome :smiley:
