### ISSUE TITLE
Warning about genome assets

### ISSUE THREAD

**Issue by gbloeb** [databio/pepatac#149]
I get following errors from all bowtie indexes that I have installed with refgenie:

/wynton/home/reiter/gloeb/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'rCRSd' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/rCRSd,/wynton/home/reit$
  warnings.warn(msg, RuntimeWarning)
/wynton/home/reiter/gloeb/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'human_repeats' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/human_repeats,/$
  warnings.warn(msg, RuntimeWarning)
/wynton/home/reiter/gloeb/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'hg38' the asset 'bowtie2_index.bowtie2_index:default' doesn't exist; tried: bowtie2_index/default/hg38,/wynton/ho$
  warnings.warn(msg, RuntimeWarning)

and for mouse:
/wynton/home/reiter/gloeb/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'mouse_chrM2x' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/mouse_chrM2x,/wy$
  warnings.warn(msg, RuntimeWarning)
/wynton/home/reiter/gloeb/.local/lib/python3.7/site-packages/refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'mm10' the asset 'bowtie2_index.bowtie2_index:default' doesn't exist; tried: bowtie2_index/default/mm10,/wynton/ho$
  warnings.warn(msg, RuntimeWarning)

**Comment by nsheff** [comment]
what do you get when you type `refgenie list` ? are you sure your `REFGENIE` variable is set correctly?

**Comment by gbloeb** [comment]
[gloeb@dev2 ~]$ refgenie list
Server subscriptions: http://refgenomes.databio.org
Local genomes: hg38, human_repeats, mm10, mouse_chrM2x, rCRSd
Local recipes: bismark_bt1_index, bismark_bt2_index, blacklist, bowtie2_index, bwa_index, cellranger_reference, dbnsfp, dbsnp, ensembl_gtf, ensembl_rb, epilog_index, fasta, fasta_txome, feat_annotation, gencode_gtf, hisat2_index, kallisto_index, refgene_anno, salmon_index, salmon_partial_sa_index, salmon_sa_index, star_index, suffixerator_index, tallymer_index
Local assets:
                hg38/   bowtie2_index:default, fasta.chrom_sizes:default, fasta.fai:default, fasta:default, feat_annotation:default, refgene_anno.refgene_exon:default, refgene_anno.refgene_intron:default, refgene_anno.refgene_pre_mRNA:default, refgene_anno.refgene_tss:default, refgene_anno:default
       human_repeats/   bowtie2_index:default
                mm10/   bowtie2_index:default, fasta.chrom_sizes:default, fasta.fai:default, fasta:default, feat_annotation:default, refgene_anno.refgene_exon:default, refgene_anno.refgene_intron:default, refgene_anno.refgene_pre_mRNA:default, refgene_anno.refgene_tss:default, refgene_anno:default
        mouse_chrM2x/   bowtie2_index:default
               rCRSd/   bowtie2_index:default



Best,
Gabe

**Comment by nsheff** [comment]
Ok -- if using bulker, is 'REFGENIE' in the list of environment variables that are passed to the bulker environment, specified in the bulker config file (in $BULKERCFG)?

for example, this is what I have in my bulker config:

```
cat $BULKERCFG
bulker:
  volumes: ['$HOME']
  envvars: ['DISPLAY', 'BIBTEXDB', 'TEXINPUTS', 'R_LIBS_USER', 'REFGENIE']
```

**Comment by gbloeb** [comment]
I get the same error whether or not I use bulker.  And when I echo $REFGENIE in my script I get the correct value, so I don’t think it’s a REFGENIE problem.
Even with these errors, the pipeline runs just fine.

Thanks for the suggestions,
Gabe

**Comment by nsheff** [comment]
The pipeline shouldn't be able to do the alignments if it can't find the bowtie2 indexes. what do you mean it runs just fine?

Ok, can you do it from the CLI: `refgenie seek hg38/bowtie2_index`?

`refgenie seek rCRSd/bowtie2_index`

**Comment by nsheff** [comment]
is it possible that these refgenie assets are stored on a filesystem that is visible to your head node, but not to the SGE compute nodes where the work is being done?

**Comment by stolarczyk** [comment]
what version of refgenie and refgenconf are you using?

```
pip freeze | grep refgen*
```

**Comment by jpsmith5** [comment]
Just to confirm this is not isolated, I also see this internally.

If I check log files I see the same runtime warning, but it depends on the genome:
```
refgenconf.py:362: RuntimeWarning: For genome 'TAIR10' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/TAIR10,/project/shefflab/genomes/bowtie2_index/TAIR10,/project/shefflab/genomes/TAIR10/bowtie2_index/default/TAIR10
  warnings.warn(msg, RuntimeWarning)
```
But it's just a warning, and if finds the correct asset without issue...

If you look at the REFGENIE config, it does seem like TAIR10 is listed differently than for genomes where I do not see this message. For example:
```
$ grep 'TAIR10' $REFGENIE
  TAIR10:
              fasta: TAIR10.fa
              fai: TAIR10.fa.fai
              chrom_sizes: TAIR10.chrom.sizes
            asset_children: ['TAIR10/bowtie2_index:default', 'TAIR10/bwa_index:default']
              bowtie2_index: TAIR10
``` 
So here, `bowtie2_index:` has its own entry. Now compare that to human.
```
$ grep -w 'hg38' $REFGENIE
  hg38:
              fasta: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_children: ['star_index:default', 'bwa_index:default', 'bowtie2_index:default', 'bismark_bt1_index:default', 'bismark_bt2_index:default', 'hg38/suffixerator_index:mjs5kd_test', 'hg38/suffixerator_index:default', 'hg38/tallymer_index:default', 'hg38/salmon_sa_index:default', 'hg38/salmon_partial_sa_index:default', 'hg38/tallymer_index:50', 'hg38/tallymer_index:40', 'hg38/tallymer_index:76', 'hg38/tallymer_index:42', 'hg38/bowtie2_index:default', 'hg38/tallymer_index:75', 'hg38/tallymer_index:100']
              gencode_gtf: hg38.gtf.gz
              ensembl_gtf: hg38.gtf.gz
            asset_children: ['feat_annotation:default', 'hg38/salmon_partial_sa_index:default']
              ensembl_rb: hg38.gff.gz
            asset_parents: ['hg38/fasta:default']
              esa: hg38.sft
            asset_parents: ['hg38/fasta:default']
            asset_children: ['hg38/tallymer_index:default', 'hg38/tallymer_index:50', 'hg38/tallymer_index:40', 'hg38/tallymer_index:76', 'hg38/tallymer_index:42',  hg38/tallymer_index:75', 'hg38/tallymer_index:100']
              tindex: hg38.tal_30
              search_file: hg38.tal_30.gtTxt
            asset_parents: ['hg38/suffixerator_index:default', 'hg38/fasta:default']
              tindex: hg38.tal_50
              search_file: hg38.tal_50.gtTxt
            asset_parents: ['hg38/fasta:default', 'hg38/suffixerator_index:default']
              tindex: hg38.tal_40
              search_file: hg38.tal_40.gtTxt
            asset_parents: ['hg38/fasta:default', 'hg38/suffixerator_index:default']
              tindex: hg38.tal_76
              search_file: hg38.tal_76.gtTxt
            asset_parents: ['hg38/suffixerator_index:default', 'hg38/fasta:default']
              tindex: hg38.tal_42
              search_file: hg38.tal_42.gtTxt
            asset_parents: ['hg38/fasta:default', 'hg38/suffixerator_index:default']
              tindex: hg38.tal_75
              search_file: hg38.tal_75.gtTxt
            asset_parents: ['hg38/fasta:default', 'hg38/suffixerator_index:default']
              tindex: hg38.tal_100
              search_file: hg38.tal_100.gtTxt
            asset_parents: ['hg38/suffixerator_index:default', 'hg38/fasta:default']
              fasta_txome: hg38.fa
              fai: hg38.fa.fai
              chrom_sizes: hg38.chrom.sizes
            asset_children: ['hg38/salmon_sa_index:default', 'hg38/salmon_partial_sa_index:default']
            asset_parents: ['hg38/fasta_txome:default', 'hg38/fasta:default']
            asset_parents: ['hg38/ensembl_gtf:default', 'hg38/fasta_txome:default', 'hg38/fasta:default']
```
There is no separate `bowtie2_index:` line entry, and samples using hg38 don't throw this warning message.



I also see the same error for mouse samples, and mm10 *does* have a `bowtie2_index:` entry.

Error:
```
refgenconf.py:362: RuntimeWarning: For genome 'mm10' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/mm10,/project/shefflab/genomes/bowtie2_index/mm10,/project/shefflab/genomes/mm10/bowtie2_index/default/mm10
  warnings.warn(msg, RuntimeWarning)
```
REFGENIE config
```
$ grep -w 'mm10' $REFGENIE
  mm10:
              ensembl_gtf: mm10.gtf.gz
            asset_children: ['feat_annotation:default', 'mm10/salmon_partial_sa_index:default']
              ensembl_rb: mm10.gff.gz
              fasta: mm10.fa
              fai: mm10.fa.fai
              chrom_sizes: mm10.chrom.sizes
            asset_children: ['star_index:default', 'bwa_index:default', 'bowtie2_index:default', 'bismark_bt1_index:default', 'bismark_bt2_index:default', 'hisat2_index:default', 'mm10/suffixerator_index:default', 'mm10/tallymer_index:default', 'mm10/salmon_sa_index:default', 'mm10/salmon_partial_sa_index:default', 'mm10/bowtie2_index:default']
              bowtie2_index: mm10
            asset_parents: ['fasta:default', 'mm10/fasta:default']
              esa: mm10.sft
            asset_parents: ['mm10/fasta:default']
            asset_children: ['mm10/tallymer_index:default']
              tindex: mm10.tal_30
              search_file: mm10.tal_30.gtTxt
            asset_parents: ['mm10/fasta:default', 'mm10/suffixerator_index:default']
              fasta_txome: mm10.fa
              fai: mm10.fa.fai
              chrom_sizes: mm10.chrom.sizes
            asset_children: ['mm10/salmon_sa_index:default', 'mm10/salmon_partial_sa_index:default']
            asset_parents: ['mm10/fasta_txome:default', 'mm10/fasta:default']
            asset_parents: ['mm10/fasta:default', 'mm10/ensembl_gtf:default', 'mm10/fasta_txome:default']
              gencode_gtf: mm10.gtf.gz
```

Just `refgenie seek`:
```
$ refgenie seek mm10/bowtie2_index
refgenconf/refgenconf.py:362: RuntimeWarning: For genome 'mm10' the asset 'bowtie2_index.None:default' doesn't exist; tried: bowtie2_index/default/mm10,/project/shefflab/genomes/bowtie2_index/mm10,/project/shefflab/genomes/mm10/bowtie2_index/default/mm10
  warnings.warn(msg, RuntimeWarning)
/project/shefflab/genomes/mm10/bowtie2_index/default/mm10

$ ls /project/shefflab/genomes/mm10/bowtie2_index/default/mm10
ls: cannot access /project/shefflab/genomes/mm10/bowtie2_index/default/mm10: No such file or directory

$ ls /project/shefflab/genomes/mm10/bowtie2_index/default
mm10.1.bt2  mm10.2.bt2  mm10.3.bt2  mm10.4.bt2  mm10.rev.1.bt2  mm10.rev.2.bt2  _refgenie_build
```

**Comment by jpsmith5** [comment]
Hmm, this may be a carry over from changes between `rgc.seek` and `rgc.get_asset` functionality within the pipeline. Let me investigate real quick.

**Comment by jpsmith5** [comment]
Okay. I still think it's something different about how those genomes are stored. I don't see anything about rgc.seek that I should be doing differently from what I can tell.  And, like I shared, `hg38` doesn't throw the error and it's the only one without a separate bowtie2_index entry in the REFGENIE file.

**Comment by stolarczyk** [comment]
For seek_key storage, because this is what you're referring to, I think: hg38 in this case stores the old style seek_key for bowtie2_index, which points to the entire tag directory (`.`):

```yaml
bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            seek_keys:
              bowtie2_index: .
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            asset_parents: ['hg38/fasta:default']
        default_tag: default
```

whereas mm10 stores the updated, correct seek_key which does not point to a file or directory, but to a path that is accepted by the actual Bowtie2 aligner

```yaml
bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            seek_keys:
              bowtie2_index: mm10
            asset_digest: 5263d8e0dde91c66f3044e18f4f4f31c
            asset_parents: ['fasta:default', 'mm10/fasta:default']
        default_tag: default
```
So in this case the ones that emit warnings are, in fact, correct... The strict check is not supposed to happen, I'll look at this.

**Comment by stolarczyk** [comment]
@gbloeb, update to `refgenconf==0.9.3` for this warning to go away.

**Comment by nsheff** [comment]
Also, just to add -- you're right that it was working correctly before, and these were just erroneous warnings. So, it is indeed just a messaging issue.

Thanks for reporting this!
