### ISSUE TITLE
Incorrectly reported number of duplicates

### ISSUE THREAD

**Issue by gbloeb** [databio/pepatac#150]
Pepatac reports that all reads are duplicates b/c it appears that it is not appropriately grabbing the data from the samblaster 
dedup_metrics_log.txt.

Dedup Metrics Log
samblaster: Version 0.1.26
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Loaded 66 header sequence entries.
samblaster: Found            0 of   14023842 (0.000%) total read ids are marked paired yet are unmated.
samblaster: Removed     374703 of   14023842 (2.672%) total read ids as duplicates using 263104k memory in 31.442S CPU seconds and 5M7S(307S) wall time.

From log:

> `Duplicate_reads`	28047690.0	PEPATAC	_RES_

> `Dedup_aligned_reads`	0.0	PEPATAC	_RES_

> `Dedup_alignment_rate`	0.0	PEPATAC	_RES_

> `Dedup_total_efficiency`	0.0	PEPATAC	_RES_

which is also propagated to stats.tsv.

I think the issue is that 
`grep 'Removed' sample_dedup_metrics_log.txt | cut -f 3 -d ' '`
gives " " when run against the dedup_metrics_log.txt, since there is more than one space between words.

[pepatac_run_mm10.txt](https://github.com/databio/pepatac/files/5164628/pepatac_run_mm10.txt)

**Comment by jpsmith5** [comment]
Huh that's strange. I don't see this in my hands.  What OS are you running on?  I do see my samblaster version is 0.1.24, but the output looks the same.  Here's an example sample in my hands:

```
cat /project/shefflab/processed/pepatac/issues/results_pipeline/SRR7866359/aligned_hg38/SRR7866359_dedup_metrics_log.txt
samblaster: Version 0.1.24
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Loaded 195 header sequence entries.
samblaster: Found 8 of 25589869 (0.00%) read ids unmated
samblaster: Please double check that input file is read-id (QNAME) grouped
samblaster: Removed 14317183 of 25589869 (55.95%) read ids as duplicates using 231504k memory in 44.850S CPU seconds and 32M7S(1927S) wall time.
```

Then, with that calll:
```
$ grep 'Removed' /project/shefflab/processed/pepatac/issues/results_pipeline/SRR7866359/aligned_hg38/SRR7866359_dedup_metrics_log.txt | cut -f 3 -d ' '
14317183
```

I'll test with the 0.1.26 version of samblaster output, maybe there are differences in the white space in that version to the one I have.

**Comment by jpsmith5** [comment]
Okay. Updated changes correctly parse version 0.1.26 from samblaster. So give it a go with the latest release and see if it looks correct on your end.
