### ISSUE TITLE
Normalization Rscript failed

### ISSUE THREAD

**Issue by gbloeb** [databio/pepatac#151]
Normalization R script failed:

Full log attached, but relevant part:

```
`Rscript pepatac/tools/PEPATAC.R reduce -i /scratch/179994.1.long.q/d4_nodnase_nobulker/peak_calling_mm10/d4_nodnase_nobulker_peaks_fixedWidth.narrowPeak -c /wynton/home/reiter/gloeb/REFGENIE/mm10/fasta/default/mm10.chrom.sizes --normalize` (28961)
<pre>
Error in if (is.na(output)) { : argument is of length zero
Calls: <Anonymous>
Execution halted
</pre>
Command completed. Elapsed time: 0:00:11. Running peak memory: 3.441GB.  
  PID: 28961;	Command: Rscript;	Return code: 1;	Memory used: 0.161GB

Child process 9760 (perl) was already terminated.
Starting cleanup: 8 files; 3 conditional files for cleanup
```

Attaching /wynton/home/reiter/gloeb/REFGENIE/mm10/fasta/default/mm10.chrom.sizes
[mm10.chrom.sizes.txt](https://github.com/databio/pepatac/files/5164702/mm10.chrom.sizes.txt)

 and the beginning of:
/scratch/179994.1.long.q/d4_nodnase_nobulker/peak_calling_mm10/d4_nodnase_nobulker_peaks_fixedWidth.narrowPeak
[d4_nodnase_nobulker_peaks_fixedWidth.narrowPeak.txt](https://github.com/databio/pepatac/files/5164719/d4_nodnase_nobulker_peaks_fixedWidth.narrowPeak.txt)

Log:
[pepatac_run_mm10.txt](https://github.com/databio/pepatac/files/5164686/pepatac_run_mm10.txt)

**Comment by jpsmith5** [comment]
Hey @gbloeb. Sorry this slipped past me. I believe this is related to your other issue (#146). My initial fix caused this message but I updated again and this should be resolved. I apologize for not passing that along to you.  Try the most recent release and see if this error disappears. If not please let me know and I'll jump on it.

**Comment by jpsmith5** [comment]
If there's still an issue please let me know and I'll reopen. Based on testing it should be resolved.
