### ISSUE TITLE
Error in single end fastq file

### ISSUE THREAD

**Issue by hiroyukikato911** [databio/pepatac#152]
Hi, 

Thank you for this wonderful pipeline.
However, I recently found when performing with **single end fastq file**, pipeline encounters error and stop processing as seen in attached file.
[error.log](https://github.com/databio/pepatac/files/5212807/error.log)

Target file comes with blank and stops.
`Target` to produce: `.gz`

Paired-end file works completely fine.
I'm using Docker and macOS High Sierra.

Any help is appreciated.

Best regards,

**Comment by jpsmith5** [comment]
Hmm. That is strange. I just successfully ran an example single-end sample successfully directly and using containers (via Singularity though not Docker).  

I do see that you're running an older version of the pipeline -- "`*     Pipeline version:  0.8.4`"

Is it important you continue using that version for a particular project? Otherwise I'd suggest updating to the most recent release as this may have been an issue that forced a version bump.

**Comment by hiroyukikato911** [comment]
Hi,

Thank you for your reply!
I decided to update pipeline version just as you recommend.

However,  installing seems to be obstacle for me.

I followed the steps just as recommended here.
http://pepatac.databio.org/en/latest/tutorial/
http://pepatac.databio.org/en/latest/install/

Namely, I cloned pepatac
```
mkdir pepatac_tutorial2
cd pepatac_tutorial2/
mkdir data
mkdir genomes
mkdir processed
mkdir templates
mkdir tools
cd tools/
git clone https://github.com/databio/pepatac.git
```
I installed refgenie and downloaded reference genome
```
pip install --user refgenie
export REFGENIE=./genomes/genome_config.yaml
refgenie init -c $REFGENIE

refgenie pull hg19/bowtie2_index
refgenie pull hg19/refgene_anno
refgenie pull hg19/feat_annotation
refgenie pull rCRSd/bowtie2_index
refgenie pull human_repeats/bowtie2_index
```

Installed bulker and load, activated the PEPATAC crate.
```
bulker load databio/pepatac -r
bulker activate databio/pepatac 
```

Now, when I run test file

`/Users/hiroyukikato/pepatac_tutorial2/tools/pepatac/pipelines/pepatac2.py --deduplicator picard --prealignments rCRSd human_repeats --genome hg19 --sample-name test1 --input /Users/hiroyukikato/pepatac_tutorial2/tools/pepatac/examples/data/test1_r1.fastq.gz --genome-size hs -O /Users/hiroyukikato/pepatac_test -P 8`

I encounter the following error.
```
tools = pm.config.tools
AttributeError: 'NoneType' object has no attribute 'tools'
### Pipeline failed at:  (09-15 21:22:54) elapsed: 0.0 _TIME_

```

Attached, please find the log file of this run.
[PEPATAC_log.txt](https://github.com/databio/pepatac/files/5224869/PEPATAC_log.txt)

I assume I encountered some basic pitfall during installation.

I really appreciate you maintaining this pipeline, as I ran many times with my previous data giving successful results.

Any help is fine.
Thanks in advance.

Best regards,

**Comment by jpsmith5** [comment]
Hey @hiroyukikato911, I'm looking into this now and will let you know briefly!

**Comment by jpsmith5** [comment]
Hey @hiroyukikato911, sorry for the long delay. You're right, it is a relatively straightforward fix, but it also prompted me to improve error messaging in just such a scenario.  I believe you are missing an environment variable that is pointing to your picard.jar file.  The pipeline is expecting to utilize a $PICARD environment variable that may look like so: `/home/user/local/bin/picard.jar`.  I imagine you don't currently have that set, so it's finding a NoneType when trying to check that command.  As I've said, I just pushed a commit to improve messaging when this happens, but the resolution for you should be as simple as setting that environment variable and trying the command again.  Let me know if you hit a snag.

**Comment by jpsmith5** [comment]
If there's still an issue let us know and we'll reopen, but it should be resolved based on prior comments.

**Comment by hiroyukikato911** [comment]
Hi,

Thanks for your help!
Also, I apologize for the delay.
I tried your solution but unfortunately didn’t work.
Perhaps other thing I might have mistaken during the installing process, so
I’m planning to retry some other solution. Since I didn’t have enough time
to dig into it, I would try again and let you know if it worked.

Thanks again for your kindness!

Best regards,
Hiroyuki



2020年9月28日月曜日 Jason Smith <notifications@github.com>:
