### ISSUE TITLE
ImportError: cannot import name 'get_logger' from 'peppy.utils'

### ISSUE THREAD

**Issue by josruirod** [databio/pepatac#153]
Hi.
Thanks for all the work and development. I'm trying to implement the pipeline in an HPC. I think I have installed everything (except for seqoutbias, I'm finding errors when compiling), but when I try to run the example as suggested in the instructions:
`looper run -d examples/test_project/test_config.yaml`

I'm getting the error:
ImportError: cannot import name 'get_logger' from 'peppy.utils' ($HOME/.local/lib/python3.8/site-packages/peppy/utils.py)

Can anybody help? Maybe some issues with the Python version?

Thanks

**Comment by stolarczyk** [comment]
could you report what versions of peppy and looper Python packages you're using?
```
pip freeze | grep looper
pip freeze | grep peppy
```

**Comment by josruirod** [comment]
Sure thank you

`loopercli==0.12.6`
`peppy==0.30.3`

**Comment by stolarczyk** [comment]
can you try uninstalling `loopercli` and installing `looper==1.2.1`?

**Comment by josruirod** [comment]
I can confirm the error I reported is now gone, thank you!

**Comment by stolarczyk** [comment]
that was actually a problem on our end, which is resolved now on dev branch. Thanks for reporting!

**Comment by jpsmith5** [comment]
Hah. Didn't mean to step on your toes @stolarczyk. Was just seeing same issue.

**Comment by stolarczyk** [comment]
what timing! 🤭
