### ISSUE TITLE
Help with the extended tutorial

### ISSUE THREAD

**Issue by josruirod** [databio/pepatac#154]
Hi and thanks for the work and the support.

I want to use the pipeline in an HPC environment and I think I have already followed the installation instructions and the instructions of the extended tutorial in [http://pepatac.databio.org/en/latest/tutorial/](url)
However, when I run `looper run examples/tutorial/tutorial.yaml` as instructed, I'm getting the error:
`Config file path isn't a file: ${REFGENIE}`

And then:
Looper finished
Samples valid for job generation: 2 of 2
Commands submitted: 2 of 2
Jobs submitted: 2

I see in the log as arguments passed to pipeline:
*        `config_file`:  `pepatac.yaml`
Maybe that's the error because that file does not exist?

Thanks for the help

**Comment by jpsmith5** [comment]
Hey @josruirod,

If you [run through the install guide prior to the tutorial](http://pepatac.databio.org/en/latest/install/), you'll see the area about setting up Refgenie.
```
2: Download refgenie assets
PEPATAC uses refgenie assets for alignment. If you haven't already, initialize a refgenie config file like this:

pip install --user refgenie
export REFGENIE=your_genome_folder/genome_config.yaml
refgenie init -c $REFGENIE
Add the export REFGENIE line to your .bashrc or .profile to ensure it persists.
```

Have you set up a REFGENIE environment variable already? 

Since I don't see it being populated in that error message, I have a feeling that hasn't been set yet.

**Comment by josruirod** [comment]
Hi,
Thank you very much for the help! You were right and this was the cause. My fault. I have now set up refgenie and the pipeline examples runs without that error.

Thank you

**Comment by jpsmith5** [comment]
You're welcome and thanks for the note regarding samtools. I will look right into that.

**Comment by jpsmith5** [comment]
Hey @josruirod, could you share the error you experienced with samtools v1.11? I have successfully run some test cases through with the updated samtools and didn't experience an error.  I'm running some more cases through now, but just curious if you could point out what it is you saw.

**Comment by jpsmith5** [comment]
Also moved this over to a new issue #155
