### ISSUE TITLE
Help with PEPATAC and non-model reference. "Required assets not existing"

### ISSUE THREAD

**Issue by josruirod** [databio/pepatac#156]
Hi 
I've been testing out PEPATAC and it looks awesome, thanks.
I'm now trying to run it with some datasets of a non-model organisms. I would say I have build all the assets with refgenie, including tallymer_index.

However, within pepatac I'm getting the following error in the "### Remove duplicates and produce signal tracks":

> Some assets are not found. You can update your REFGENIE config file or point directly to the file using the noted command-line arguments:
Starting cleanup: 4 files; 3 conditional files for cleanup

Then I think relevant lines in the pipeline failed message are:

> Failure reason: Required assets not existing: tallymer_index.search_file:75 (--search-file)

> OSError: Required assets not existing: tallymer_index.search_file:75 (--search-file)

However, I have built tallymer_index and I'd say it didn't failed. Could anyone please point me to the issue or to which are the assets not found? (I may not be able to get them to my organisms of interest, since it may not be that well studied or annotated, some way of skipping this then?)

Thanks for the help

**Comment by nsheff** [comment]
can you show the output of `refgenie list` ? And what genome are you using?

**Comment by josruirod** [comment]
Ok, thanks

output of `refgenie list`:
> Server subscriptions: http://refgenomes.databio.org
Local genomes: AgamP
Local recipes: bismark_bt1_index, bismark_bt2_index, blacklist, bowtie2_index, bwa_index, cellranger_reference, dbnsfp, dbsnp, ensembl_gtf, ensembl_rb, epilog_index, fasta, fasta_txome, feat_annotation, gencode_gtf, hisat2_index, kallisto_index, refgene_anno, salmon_index, salmon_partial_sa_index, salmon_sa_index, star_index, suffixerator_index, tallymer_index
Local assets:
               AgamP/   bowtie2_index:default, ensembl_gtf.ensembl_gene_body:default, ensembl_gtf.ensembl_tss:default, ensembl_gtf:default, fasta.chrom_sizes:default, fasta.fai:default, fasta:default, gencode_gtf:default, refgene_anno.refgene_exon:default, refgene_anno.refgene_intron:default, refgene_anno.refgene_pre_mRNA:default, refgene_anno.refgene_tss:default, refgene_anno:default, suffixerator_index.esa:default, tallymer_index.search_file:default, tallymer_index.tindex:default

I'm trying to use the genome Anopheles gambiae

**Comment by jpsmith5** [comment]
Hey @josruirod,

I see you have a default tallymer_index asset. The default is for 30. It looks like based on messaging you need one for 75.  You can check out the [seqOutBias documentation for more information.](http://pepatac.databio.org/en/latest/sob/) But basically, you'll need to generate a tallymer index for 75bp.

`refgenie build AgamP/tallymer_index:75 --params mersize=75`

Believe that would be the appropriate build command for your genome here. Give that a try and confirm it resolves the issue.

**Comment by josruirod** [comment]
Hi, I can confirm it's working now. Thanks again for the help
