### ISSUE TITLE
MACS2 step failing because the input bed file does not have strand info?

### ISSUE THREAD

**Issue by josruirod** [databio/pepatac#157]
Hi, and thanks for the support.

I'm struggling to get pepatac working for the first time with our own samples. Almost everything seems to be working now (thanks for the help in previous steps!). But I have now encountered an error with MACS2. 
I'm getting the error:

> MACS2.IO.Parser.StrandFormatError: 'Strand information can not be recognized in this line: "b\'chr2L\\t1119\\t1120\\tN\\t\\t0.6812304791\'","b\'0.6812304791\'"'

And indeed, the file that macs2 is trying to use in BED format is:

> /out_pepatac/test1/aligned_test_exact/test1_shift.bed

And the head is:

> chr2L	1119	1120	N		0.6812304791
chr2L	1124	1125	N		2.177074836
chr2L	1130	1131	N		0.8319069562

Indeed, there is no information on the strand, which is needed for the BED mode according to the macs2 manual. I'm not sure when did I lose it.  I have tried to look before in the pipeline but there were no errors. I have read again the pepatac documentation but I'm not sure what I'm missing. I'm unsure where is this file coming from, but I ran the pipeline with `--sob`, in case it's coming from there.

Thanks you again for your support!

**Comment by jpsmith5** [comment]
Could you share your entire PEPATAC_log.md file? You'll need to change the extension to `.txt` for github. But then you should just be able to drag the file into the comment box to share it.

**Comment by josruirod** [comment]
Sure thing, thanks. It may contain several calls to the pipeline with different testing, but the last ones are the ones reaching macs2 and giving that error.

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/5386788/PEPATAC_log.txt)

**Comment by jpsmith5** [comment]
Hey @josruirod, this turned out be where I had accidentally written over my own solution to this problem from the past. Just released a new version (0.9.7) of the pipeline that resolves this. Sorry for the additional challenge.

You can add the `-R` command to recover the pipeline run instead of starting from scratch. You will have to manually delete the current `*_shift.bed` file. So, `rm /scratch-global/data/1020_ATAC/out_pepatac/test1/aligned_AgamP_exact/test1_shift.bed` in this case. Then you should be able to resume where it left off. Again, sorry for the extra challenge.

**Comment by josruirod** [comment]
No problem at all, glad to help. I'll test the new version and let you know, thanks again for the support.

**Comment by josruirod** [comment]
Hi, I have installed the new version (0.9.7, checked with pepatac.py --version), and it seems to run ok. However, again in the macs2 step, something it's wrong. I'm getting:

> Total time: 3:21:00
Failure reason: Subprocess returned nonzero result. Check above output for details
Traceback (most recent call last):
  File "/home/ipbln/jlruiz/bin/pepatac/pipelines/pepatac.py", line 2658, in <module>
    sys.exit(main())
  File "/home/ipbln/jlruiz/bin/pepatac/pipelines/pepatac.py", line 1970, in main
    pm.run(cmd, peak_output_file, follow=report_peak_count)
  File "/home/ipbln/jlruiz/.local/lib/python3.8/site-packages/pypiper/manager.py", line 785, in run
    self.callprint(cmd, shell, lock_file, nofail, container)  # Run command
  File "/home/ipbln/jlruiz/.local/lib/python3.8/site-packages/pypiper/manager.py", line 1028, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/home/ipbln/jlruiz/.local/lib/python3.8/site-packages/pypiper/manager.py", line 2131, in _triage_error
    self.fail_pipeline(e)
  File "/home/ipbln/jlruiz/.local/lib/python3.8/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details

Above in the screen I can only see in the macs2 step that it has been killed for some reason:

> Command completed. Elapsed time: 0:00:12. Running peak memory: 3.456GB.  
  PID: 4083;	Command: macs2;	Return code: -9;	Memory used: 0.024GB

But I don't see any more info. I'm attaching again the full pipeline log. Hope you have any advice, thank you very much for your availability!
[PEPATAC_log.txt](https://github.com/databio/pepatac/files/5396442/PEPATAC_log.txt)

**Comment by jpsmith5** [comment]
Hey @josruirod. Yeah you're right. Looks like MACS2 just failed mid-step.  

What version of macs2 are you currently running? e.g. `macs2 --version`

If you try running the macs2 command manually, i.e. just copying and pasting the same command as the pipeline, what happens?

e.g.:
```
macs2 callpeak -t /scratch-global/jlruiz/data/1020_ATAC_mosquitoes/out_pepatac/test1/aligned_AgamP_exact/test1_shift.bed -f BED --outdir /scratch-global/jlruiz/data/1020_ATAC_mosquitoes/out_pepatac/test1/peak_calling_AgamP -n test1 -g 264974304 --shift -75 --extsize 150 --nomodel --call-summits --nolambda --keep-dup all -p 0.01
```

Just curious if it's a macs2 problem potentially, a pipeline issue, or maybe a local computing issue.  I've run several samples with the same settings you've got here and they are completing without an error, so the source of the problem is still unclear to me, but will keep testing.

**Comment by josruirod** [comment]
Hi,
MACS2 is 2.2.7.1, and if I run the command separately, it starts to run but then suddenly 

> INFO  @ Sun, 18 Oct 2020 09:28:04:  6000000 
Killed

Weird. The `test1_shift.bed` seems ok. Which macs2 version are you using? Thanks

**Comment by jpsmith5** [comment]
Hey, that's the version I'm running as well. That seems suggestive of it being killed off by a resource handler. I don't normally see macs2 consume enormous amounts of memory, but that would be a reason for it to be killed. Are you able to test that command in an environment with copious amounts of memory? I'll keep looking into additional possibilities too.

**Comment by nsheff** [comment]
That looks like it's run on a head node of a cluster, which kills it when the memory exceeds the limit. are you using SLURM by chance? you'd need to do this test in an allocation.

**Comment by josruirod** [comment]
Hi and thanks for your help. I'm not sure why and I've never seen MACS2 require much memory either, but indeed I can confirm that allocating more memory seems to solve the problem and everything is running fine.

Thanks again for the help

**Comment by jpsmith5** [comment]
:+1: If anything else pops up let us know.
