### ISSUE TITLE
cannot run demo

### ISSUE THREAD

**Issue by Honchkrow** [databio/pepatac#162]
Hello, 
  I followed the tutorial in "4: Run an example project through PEPATAC" to run the demo, but encountered the following error.
`
(pepatac) [wzhang@localhost pepatac]$ cd /disk/wzhang/software/pepatac
(pepatac) [wzhang@localhost pepatac]$ looper run -d examples/test_project/test_config.yaml
Looper version: 1.3.0
Command: run
Not all environment variables were populated in derived attribute source: $CODE/pepatac/examples/data/{sample_name}_r1.fastq.gz
Not all environment variables were populated in derived attribute source: $CODE/pepatac/examples/data/{sample_name}_r2.fastq.gz
Ignoring invalid pipeline interface source: /disk/wzhang/software/pepatac/examples/test_project/$CODE/pepatac/sample_pipeline_interface.yaml. Caught exception: FileNotFoundError(2, 'No such file or directory')
> Not submitted: No pipeline interfaces defined

Looper finished
Samples valid for job generation: 0 of 1
Commands submitted: 0 of 0
Jobs submitted: 0
Dry run. No jobs were actually submitted.

1 unique reasons for submission failure: No pipeline interfaces defined

Summary of failures:
No pipeline interfaces defined: test1
(pepatac) [wzhang@localhost pepatac]$
`
  I followed the tutorial every step and sure all the dependencies, even the optinal, are satisfied. It seems that the variable in yaml file do not correct, can you help me about this?
  Thank you !
Honchkrow

**Comment by jpsmith5** [comment]
Hey @Honchkrow, sorry I didn't have a chance to respond here. This looks like an environment variable issue, and clearly I didn't document this well enough. The `$CODE` environment variable is used to provide the path to the parent directory containing the `pepatac/` repository. 

So, in this case it would likely be set like so based on what I see here: `export CODE=/disk/wzhang/software/`

Give that a try and see if it behaves as you'd expect.
