### ISSUE TITLE
running example project

### ISSUE THREAD

**Issue by pegahtak** [databio/pepatac#163]
Hello 
I have installed all the required softwares and tried to run the example project 
```
cd pepatac
looper run -d examples/test_project/test_config.yaml
```
but I get this error message 

```
Looper version: 1.3.0
Command: run
Ignoring invalid pipeline interface source: /pepatac/sample_pipeline_interface.yaml. Caught exception: FileNotFoundError(2, 'No such file or directory')
> Not submitted: No pipeline interfaces defined

Looper finished
Samples valid for job generation: 0 of 1
Commands submitted: 0 of 0
Jobs submitted: 0
Dry run. No jobs were actually submitted.

1 unique reasons for submission failure: No pipeline interfaces defined

Summary of failures:
No pipeline interfaces defined: test1
```
is there a way I could I fix this?

I would appreciate your help

**Comment by stolarczyk** [comment]
looper is looking for the pipeline interface file in `/pepatac/sample_pipeline_interface.yaml` and this file does not exist.

I presume you're using this project config: https://github.com/databio/pepatac/blob/master/examples/test_project/test_config.yaml. It points to the pipeline interface in this line: https://github.com/databio/pepatac/blob/3291788027375c57fbf76ed36ffd9349a8c463bc/examples/test_project/test_config.yaml#L13

Therefore, you need to set the environment variable `$CODE` to point to the place where the `pepatac` directory is located.

**Comment by pegahtak** [comment]
thank you @stolarczyk . I set CODE env variable accordingly. when I run `looper run -d examples/test_project/test_config.yaml`  I get :
```
Looper version: 1.3.0
Command: run

## [1 of 1] sample: test1; pipeline: PEPATAC
Writing script to /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Job script (n=1; 0.00Gb): /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Dry run, not submitted

Looper finished
Samples valid for job generation: 1 of 1
Commands submitted: 1 of 1
Jobs submitted: 1
Dry run. No jobs were actually submitted.
```
but  when I try to `run looper run examples/test_project/test_config.yaml`

```
Looper version: 1.3.0
Command: run
## [1 of 1] sample: test1; pipeline: PEPATAC
Writing script to /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Job script (n=1; 0.00Gb): /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Compute node: ibb-server
Start time: 2021-01-27 12:49:07
Traceback (most recent call last):
  File "/home/ptaklifi/pepatac/pipelines/pepatac.py", line 16, in <module>
    import pypiper
ImportError: No module named pypiper

Looper finished
Samples valid for job generation: 1 of 1
Commands submitted: 1 of 1
Jobs submitted: 1
```

**Comment by nsheff** [comment]
go back through the instructions carefully and make sure you've got everything installed:  http://pepatac.databio.org/en/latest/install/ 

pypiper is installed in the python packages step under 'install required software'.

**Comment by pegahtak** [comment]
thank you @nsheff . like tutorial ,through pepatac/ directory I run this command : 
`pip install --user -r requirements.txt`
to make sure also 
`pip install pypiper `

but I still see the same error message 

`Looper version: 1.3.0
Command: run

## [1 of 1] sample: test1; pipeline: PEPATAC
Writing script to /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Job script (n=1; 0.00Gb): /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub
Compute node: ibb-server
Start time: 2021-01-27 16:35:00
Traceback (most recent call last):
  File "/home/ptaklifi/pepatac/pipelines/pepatac.py", line 16, in <module>
    import pypiper
ImportError: No module named pypiper

Looper finished
Samples valid for job generation: 1 of 1
Commands submitted: 1 of 1
Jobs submitted: 1
`

**Comment by stolarczyk** [comment]
pypiper is piper on PyPi: https://pypi.org/project/piper/

run: 

```
pip install piper
```

**Comment by pegahtak** [comment]
thank you @stolarczyk  for your response. when I try to open `pipelines/pepatac.py ` with python ( which I think refers to python2) `python  pepatac/pipelines/pepatac.py` I get this errror 
```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 16, in <module>
    import pypiper
ImportError: No module named pypipe
```
but when I try python3 : `python3 pipelines/pepatac.py` I get the following message :

```
usage: pepatac.py [-h] [-R] [-N] [-D] [-F] [-T] [--silent] [--verbosity V]
                  [--logdev] [-C CONFIG_FILE] -O PARENT_OUTPUT_FOLDER
                  [-M MEMORY_LIMIT] [-P NUMBER_OF_CORES] -S SAMPLE_NAME -I
                  INPUT_FILES [INPUT_FILES ...]
                  [-I2 [INPUT_FILES2 [INPUT_FILES2 ...]]] -G GENOME_ASSEMBLY
                  [-Q SINGLE_OR_PAIRED] [--aligner {bowtie2,bwa}]
                  [--peak-caller {fseq,genrich,hmmratac,homer,macs2}]
                  [-gs GENOME_SIZE] [--trimmer {trimmomatic,pyadapt,skewer}]
                  [--prealignments PREALIGNMENTS [PREALIGNMENTS ...]]
                  [--deduplicator {picard,samblaster,samtools}]
                  [--TSS-name TSS_NAME] [--blacklist BLACKLIST]
                  [--anno-name ANNO_NAME] [--peak-type {fixed,variable}]
                  [--extend EXTEND] [--frip-ref-peaks FRIP_REF_PEAKS]
                  [--motif] [--sob] [--no-scale] [--prioritize] [--keep]
                  [--noFIFO] [--lite] [--skipqc] [-V]
pepatac.py: error: the following arguments are required: -O/--output-parent, -S/--sample-name, -I/--input, -G/--genome 
```

**Comment by stolarczyk** [comment]
The former failed because you didn't install piper for python2. 

The latter worked, you just didn't provide the arguments to perform the analysis. You can do so by creating a PEP and running pepatac with looper which is described in the tutorials.

**Comment by pegahtak** [comment]
thank you @stolarczyk. we set looper to use python3 instead of python2 ;

```
looper run examples/test_project/test_config.yaml

Looper version: 1.3.0
Command: run
## [1 of 1] sample: test1; pipeline: PEPATAC
> Skipping sample because no failed flag found. Flags found: ['/home/ptaklifi/pepatac_test/results_pipeline/test1/PEPATAC_failed.flag']
Writing 1 submission scripts for skipped samples
Writing script to /home/ptaklifi/pepatac_test/submission/PEPATAC_test1.sub

Looper finished
Samples valid for job generation: 1 of 1
Commands submitted: 0 of 1
Jobs submitted: 0
```

**Comment by pegahtak** [comment]
.
