### ISSUE TITLE
set env vars in the "Install and run test example" tutorial

### ISSUE THREAD

**Issue by stolarczyk** [databio/pepatac#164]
Consider adding a suggestion to set environment variables used in [this PEP](https://github.com/databio/pepatac/blob/master/examples/test_project/test_config.yaml) on [this page](http://pepatac.databio.org/en/latest/install/). 

Currently running the steps in the tutorial leads to issues like this one: #163

**Comment by nsheff** [comment]
Or, maybe the demo/tutorial PEP should not be using environment variables, if we can avoid it...

**Comment by jpsmith5** [comment]
Adjusted to have everything be relative to pepatac/ directory for this test case
