### ISSUE TITLE
Sample with multiple R1 and R2 reads

### ISSUE THREAD

**Issue by arpanda** [databio/pepatac#170]
How to provide input when a sample has multiple R1 and R2 fastq file?

I have few samples with 2 R1 read and 2 R2 reads. How can I process them using pepatac?

**Comment by nsheff** [comment]
http://pep.databio.org/en/latest/howto_multiple_inputs/

**Comment by nsheff** [comment]
there are some examples also, such as: https://github.com/pepkit/example_peps/tree/master/example_subtable4

**Comment by arpanda** [comment]
Thanks.
