### ISSUE TITLE
is it possible to use aligned bam files as input ?

### ISSUE THREAD

**Issue by pegahtak** [databio/pepatac#172]
Hello and thanks for great work. It's not an issue that I'm writing about but a question, so if it's irrelevant please let me know to delete or close this. 
I have about 250 aligned and deduplicated bam files that were aligned with bowtie2 and deduplicated using picard MarkDuplicates . I was wondering if I could use these bam files as input for pepatac ?
Thank you

**Comment by jpsmith5** [comment]
Hey @pegahtak, you would need to revert them (with Picard) to either an unaligned bam or generate fastq files from those.

For example: `java -jar picard.jar RevertSam I=input.bam O=output_reverted.bam VALIDATION_STRINGENCY=LENIENT`

Or: `bedtools bamtofastq -i input.bam -fq output_r1.fq -fq2 output_r2.fq`

See if that approach would work for you.

**Comment by pegahtak** [comment]
Thank you @jpsmith5
