### ISSUE TITLE
Generating count table

### ISSUE THREAD

**Issue by wangjiawen2013** [databio/pepatac#174]
Hi,
Is there a way to generate count table without using looper ? I mean, generate count table by running the pipeline script directly for each sample and then produce a count table for all the samples.

**Comment by jpsmith5** [comment]
Hi @wangjiawen2013, did you try [looking over the guide here](http://pepatac.databio.org/en/latest/count_table/)?  You should be able to run the table generation in R, but it does still expect a PEP setup for your project.  Take a look at that and then I'm happy to help troubleshoot downstream.
