### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by vreuter** [databio/pepatac#18]
Is the TSS enrichment analysis expected to be done quite frequently (or always)? If so, I think it may be good to add the dependencies for `tools/pyTssEnrichment.py` to the project requirements file. We get `numpy` from the `looper` dependency on `pandas` and `pysam` from the `pararead` dependency, but we don't have `matplotlib` explicitly or implicitly. That's probably a relatively big one, so if the TSS enrichment won't be used super frequently, it's probably best to handle it through a secondary requirements installation/enforcement mechanism, but otherwise I think that we may want to add it to the main `requirements.txt`.

**Comment by jpsmith5** [comment]
Looks like everything this was concerned about has since been addressed regarding usage and with plotting being taken over in R.  Closing for now.
