### ISSUE TITLE
HMMRATAC as peak caller - Peaks folder output

### ISSUE THREAD

**Issue by pratimanl** [databio/pepatac#180]
Hello, 

We're running PEPATAC using HMMRATAC as peak caller. 

Is it expected to see "HMMRATAC failed to identify any peaks." in the log file and an empty .narrowPeak file, because HMMRATAC instead generates the .gappedPeak and summits.bed? Also, attached a screenshot of the peaks folder for one of the samples, are these the expected output?

<img width="567" alt="Screen Shot 2021-05-17 at 10 49 25 AM" src="https://user-images.githubusercontent.com/31975131/118534002-9b18b180-b6fd-11eb-9d39-f31e4aabcabc.png">

Thank you for your help,
Pratima

**Comment by jpsmith5** [comment]
Hi @pratimanl, yes I've recently uncovered some bugs with changes to the pipeline that are now fixed in the development branch.  You can check that out or if you wait a day, I'm close to releasing those updates that should address this for you.

**Comment by pratimanl** [comment]
Thank you @jpsmith5. Updating our pepatac version is a pending task, so for now we are continuing with pepatac version 0.9.10, and would like to see if the following issue is really a java memory issue or something we need to troubleshoot within pepatac code: 

Snippet of log file of one of the samples which generated fewer than expected output files:

> Target to produce: `..._peaks.narrowPeak`  		
> > `java -jar .../software/hmmratac/1.2.10/HMMRATAC.jar --bam ..._fixed_header.bam --index ..._fixed_header.bam.bai --genome .../peak_calling_Sscrofa11_1/chr_order.txt --output .../peak_calling_Sscrofa11_1/P452-2_peaks.narrowPeak` (99376)		
> <pre>		
> 
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space | &nbsp; | &nbsp;
> &nbsp; | at java.base/java.util.Arrays.copyOf(Arrays.java:3688) | &nbsp; | &nbsp;
> &nbsp; | at java.base/java.util.ArrayList.grow(ArrayList.java:237) | &nbsp; | &nbsp;
> &nbsp; | at java.base/java.util.ArrayList.grow(ArrayList.java:242) | &nbsp; | &nbsp;
> &nbsp; | at java.base/java.util.ArrayList.add(ArrayList.java:467) | &nbsp; | &nbsp;
> &nbsp; | at java.base/java.util.ArrayList.add(ArrayList.java:480) | &nbsp; | &nbsp;
> &nbsp; | at FormatConverters.PileupToBedGraph.toMap(PileupToBedGraph.java:114) | &nbsp; | &nbsp;
> &nbsp; | at FormatConverters.PileupToBedGraph.run(PileupToBedGraph.java:50) | &nbsp; | &nbsp;
> &nbsp; | at FormatConverters.PileupToBedGraph.&lt;init&gt;(PileupToBedGraph.java:41) | &nbsp; | &nbsp;
> &nbsp; | at WigMath.pileup.toBedGraph(pileup.java:217) | &nbsp; | &nbsp;
> &nbsp; | at WigMath.pileup.build(pileup.java:206) | &nbsp; | &nbsp;
> &nbsp; | at WigMath.pileup.&lt;init&gt;(pileup.java:71) | &nbsp; | &nbsp;
> &nbsp; | at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)

We're currently trying change to java usage - something like "java -Xms1g -Xmx7g -jar ..." in the pepatac.py file.

Do you have any input on how to go about this? Or is this part of the list of fixes you've already made?

Thank you for your help

**Comment by jpsmith5** [comment]
Hey @pratimanl, I've just released a version that should ease this process. You can specify additional java based parameters in the `pepatac.yaml` configuration file under the `java_settings:` header. Any step that requires a `java` call would append these settings to the `java` call itself.

Similarly, there's also the built in `JAVA_TOOL_OPTIONS` environment variable you could set to modify your java settings system wide.
