### ISSUE TITLE
Should checkinstall check for refgenie assets?

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#196]
Right now, checkinstall doesn't confirm that you have all the refgenie assets you need.

Would that be a useful addition?

**Comment by jpsmith5** [comment]
I guess since it's determinate of genomes of interest of the user? But, for the test example, we could have it check, since you *will* need those? Is that your thought?

**Comment by nsheff** [comment]
Ah, you're right that it depends on the user's choice of genomes.

Just think it might be convenient to help the user easily check if they have all the assets they need, somehow. I guess it would require having them give a list of genomes (main + prealignments), or a PEP...

So I guess this is a bit separate from checkinstall. it's like, checkassets or something.

**Comment by jpsmith5** [comment]
Now that `refgenie` is no longer an explicit requirement, this sort of check remains even more dependent on an individual user. Will return to this should be it make sense again in a new light.
