### ISSUE TITLE
Number of regions

### ISSUE THREAD

**Issue by wangjiawen2013** [databio/pepatac#200]
Hi,
what does the y-axis label "number of regions" mean in the plot of Distribution of peaks over the genome. The number looks the same (all are 189 in the following image). Is it the coverage, fold change or something else ? Can I compare it among different samples ? And, only readks within the peaks are displayed or all reads mapped to the genome are displayed on the plot ?
![捕获](https://user-images.githubusercontent.com/29703450/126925888-01bc97b7-f66a-4999-8150-e2665ed9ee21.PNG)

**Comment by jpsmith5** [comment]
- what does the y-axis label "number of regions" mean in the plot of Distribution of peaks over the genome. 

This represents the counts of regions from the query (the peak file) that overlap with each binned chromosome. You can [read more about this function here](http://code.databio.org/GenomicDistributions/reference/calcChromBinsRef.html).

- Can I compare it among different samples ?

Independently it can serve as a quick snapshot of the distribution across chromosomes, but the y-axis scale would shift based on the separate sample.  Now, [you can, using the full Genomic Distributions package, plot samples on the same plot](http://code.databio.org/GenomicDistributions/articles/intro.html#chromosome-distribution-plots).  That would serve as a better cross sample comparison if you wanted to observe samples on the same y-axis. And if you wanted some guidance beyond what the link shows, I'm happy to walk you through this.

- And, only readks within the peaks are displayed or all reads mapped to the genome are displayed on the plot ?

The former, it is just reads within in peaks, *not* all mapped reads.

**Comment by wangjiawen2013** [comment]
Thanks for you help, it's very valuable !
I tried to plot samples manually using:
query1 = rtracklayer::import("./WT_peaks_normalized.narrowPeak")
x = calcChromBinsRef(query1, "mm10")
plotChromBins(x).
however, the plot is different from that genereated by PEPATAC default pipeline. contigs that cannot be confidently placed on a specific chromosome were also displayed. I checked the narrowPeak file and I am sure that there are no peaks on the contis, but it shows some peaks on the plot. which narrowpeak should I use ?
![捕获](https://user-images.githubusercontent.com/29703450/127083208-8e76b18b-e57e-475b-b1de-21689e675e1d.PNG)

**Comment by jpsmith5** [comment]
With your `x` object returned from `calcChromBinsRef()` you can remove the lowest 10% represented genomes to effectively drop all those unassigned and random chromosomes.

e.g.
```
tbl      <- data.frame(table(x$value$chr))
cutoff <- quantile(tbl$Freq, 0.1)
keep   <- tbl[tbl$Freq > cutoff, 1]
x         <- x$value[x$value$chr %in% keep,]
ga_plot <- plotChromBins(x)
```
