### ISSUE TITLE
PEPATACr no longer available 

### ISSUE THREAD

**Issue by gbloeb** [databio/pepatac#213]
When I try to install PEPATACr I get following error:

```
> devtools::install(file.path("PEPATACr/"), dependencies=TRUE, repos="https://cloud.r-project.org/")
Error: [ENOENT] Failed to realize 'PEPATACr': no such file or directory
```

**Comment by jpsmith5** [comment]
Hey @gbloeb, can you confirm you're in the pipeline repository parent folder when executing that command? It's expecting the `file.path("PEPATACr/")` to be in the `pepatac/` folder.

**Comment by gbloeb** [comment]
You're right, I wasn't doing this from the pepatac directory and was clearly there in the install instructions.  Sorry for troubling you about this.  And thank you for fixing the conda install back in November!
