### ISSUE TITLE
Where are Supplemental Files 1..4 ?

### ISSUE THREAD

**Issue by kloot** [databio/pepatac#225]
All hyperlinks to these files on the NARGB page point to 'lqab101_supplemental_file.pdf', but the xlsx and csv files aren't included.

Many thanks in advance!

**Comment by jpsmith5** [comment]
Hi @kloot, these are all available on the web through the following links. Let me know if there's any issue retrieving them.

- [Supplemental_file_1.csv](http://big.databio.org/pepatac/Supplemental_file_1.csv)
- [Supplemental_file_2.xlsx](http://big.databio.org/pepatac/Supplemental_file_2.xlsx)
- [Supplemental_file_3.xlsx](http://big.databio.org/pepatac/Supplemental_file_3.xlsx)
- [Supplemental_file_4.csv](http://big.databio.org/pepatac/Supplemental_file_4.csv)
