### ISSUE TITLE
eido 0.2.0 has changes that break pepatac 

### ISSUE THREAD

**Issue by molecules** [databio/pepatac#244]
Try installing and running pepatac from scratch and you'll find multiple changes in the transition from eido 0.1.9 to 0.2.0 that breaks the code, including but not limited to:

* `validate_inputs` function replaced with `validate_input_files` 
* `validate_config` and `validate_sample` each now take one fewer parameter

**Comment by donaldcampbelljr** [comment]
Newest point release https://github.com/databio/pepatac/releases/tag/v0.10.4 fixes both the Looper and Eido requirements. Doing a fresh install of the environment should now work when installing pepatac from scratch.
