### ISSUE TITLE
looper bug. I change looper version from 1.4.3 to 1.3.0. How can I debug? Please help, thanks!!!!

### ISSUE THREAD

**Issue by Conskier** [databio/pepatac#248]
$ databio/pepatac|~/project/pepatac_tutorial/tools/pepatac$ looper run examples/tutorial/tutorial_refgenie.yaml
Traceback (most recent call last):
  File "/home/data/t080402/.local/bin/looper", line 5, in <module>
    from looper.__main__ import main
  File "/home/data/t080402/.local/lib/python3.8/site-packages/looper/__init__.py", line 13, in <module>
    from .conductor import SubmissionConductor
  File "/home/data/t080402/.local/lib/python3.8/site-packages/looper/conductor.py", line 15, in <module>
    from eido import read_schema, validate_inputs
ImportError: cannot import name 'validate_inputs' from 'eido' (/home/data/t080402/.local/lib/python3.8/site-packages/eido/__init__.py)

**Comment by donaldcampbelljr** [comment]
Hello,

Did you solve your issue? We've since released newer versions of PEPATAC, Looper, and Pipestat within the last month that may work better for you.

**Comment by nsheff** [comment]
This was likely solved in an update to the eido package, but please comment on this issue again or open a new issue if you find a similar problem
