### ISSUE TITLE
Skipping 1 packages not available: pepr

### ISSUE THREAD

**Issue by TianJie327** [databio/pepatac#250]
I'm having the following problem installing the package, if you can help me I'd appreciate it!

> devtools::install(file.path("PEPATACr/"))
Skipping 1 packages not available: pepr
✔  checking for file ‘/gdata01/user/tianjie/lpp_file/pepatac/pepatac-master/PEPATACr/DESCRIPTION’ (405ms)
─  preparing ‘PEPATACr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘PEPATACr_0.0.1.0000.tar.gz’

Running /gdata01/apps/miniconda3/envs/pepatac/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpdFYEcr/PEPATACr_0.0.1.0000.tar.gz --install-tests
* installing to library ‘/gdata01/apps/miniconda3/envs/pepatac/lib/R/library’
ERROR: dependency ‘pepr’ is not available for package ‘PEPATACr’
* removing ‘/gdata01/apps/miniconda3/envs/pepatac/lib/R/library/PEPATACr’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occurred
> Skipping 1 packages not available: pepr
✔  checking for file ‘/gdata01/user/tianjie/lpp_file/pepatac/pepatac-master/PEPATACr/DESCRIPTION’ (405ms)
─  preparing ‘PEPATACr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘PEPATACr_0.0.1.0000.tar.gz’

**Comment by nsheff** [comment]
At the time last year, there was an issue with CRAN, which had pulled the `pepr` package due to an error contacting the maintainer email address. This was solved with the pepr 0.5.0 release in November of 2023, so this is no longer a problem.
