### ISSUE TITLE
looper runp looper.pep_config output None --solved

### ISSUE THREAD

**Issue by miximimi** [databio/pepatac#267]
I am not sure if this is already fixed in the newest version, but when I am running the older vesion of pepatac this following bug appeared: 

When running looper runp project_config.yaml, project_pipeline_interface.yaml tries to pass --config {looper.pep_config} to pepatac_collator.py but this is not defined anywhere. What I did was changing this to --config {looper.config_file} and added `config_file: {my project_config.yaml path}` into the looper section of project_config.yaml, and do the rerun. Now this config yaml can be correctly passed to the .py and .R scripts. 

If this is already solved in the newest version, feel free to ignore or delete this trend. 

Thank you!

**Comment by donaldcampbelljr** [comment]
Hey, thanks for posting. The preferred way to run everything with the newest changes:
`looper run --looper-config /your/path/.looper_config.yaml` and 
`looper runp --looper-config /your/path/.looper_config.yaml`

For a specific example from the tutorial (in pepatac/tutorial/examples):
`looper run --looper-config .looper_tutorial_refgenie.yaml`

Further reading (this affects Looper 1.5.0 and greater):
https://looper.databio.org/en/latest/looper-config/
https://github.com/pepkit/hello_looper

**Comment by donaldcampbelljr** [comment]
Since this is solved, I will close.
