### ISSUE TITLE
Error: Install the "PEPATACr" R package before proceeding.

### ISSUE THREAD

**Issue by DavideBrex** [databio/pepatac#275]
Hi,
thank you for this nice tool.

I am trying to run the tutorial (http://pepatac.databio.org/en/latest/tutorial/) using the singularity image. However, the execution stops, and I get an error related to PEPATACr:
Error: Install the "PEPATACr" R package before proceeding.
[PEPATAC_log (copy).txt](https://github.com/databio/pepatac/files/14614205/PEPATAC_log.copy.txt)
I checked, and the R package is installed inside the container. I also installed it on my local machine but still I get the same error.

Thank you for your support.
Best,

Davide

**Comment by nsheff** [comment]
@DavideBrex  -- were you able to solve the problem?

**Comment by DavideBrex** [comment]
yes, there was an issue with my local installation of PEPATACr on my local machine. Now it works. Still, I did not manage to set singularity to use the R libraries within the container instead of my local ones.  I tried to add the "-e" flag to the singularity arguments, but it did not work.
