### ISSUE TITLE
'Pipestat compatible': False, 'Commands submitted': '0 of 8', 'Jobs submitted': 0

### ISSUE THREAD

**Issue by ChangshengWei97** [databio/pepatac#276]
I performed the guide, it seems OK, but 0 commands were submitted, like:
![2](https://github.com/databio/pepatac/assets/161601833/12425085-40ae-431d-b8d3-28346ccf8e3d)

**Comment by ChangshengWei97** [comment]
![Uploading 1.png…]()

**Comment by ChangshengWei97** [comment]
![1](https://github.com/databio/pepatac/assets/161601833/f15c13d5-3749-4b82-bc98-a23feb53799e)

**Comment by donaldcampbelljr** [comment]
Based on the first screenshot, the pipeline failed and now has `failed.flag`s. If Looper sees these flags, it will skip the sample. You can either:
- manually delete the flag
- use the rerun command
- use the ignoreflags argument

I would recommend determining what caused the pipeline failure. There should be clues in the `PEPATAC_log.md` file.

**Comment by donaldcampbelljr** [comment]
Hi @ChangshengWei97 , were you able to get this to work as expected?

**Comment by donaldcampbelljr** [comment]
Hi @ChangshengWei97 I will close this for now. Please reopen if you continue to have issues.
