### ISSUE TITLE
is the pararead dependency required?

### ISSUE THREAD

**Issue by mbassalbioinformatics** [databio/pepatac#286]
Hi 

im trying to install pepatac through conda and the pararead package keeps erroring out and wont install. can i skip it in the requirements install and still be able to use the pipeline or is this an essential component and will break the whole pipeline if not installed?

**Comment by nsheff** [comment]
It's essentially. @khoroshevskyi will look into this today and try to get you a working installation of pararead.

**Comment by mbassalbioinformatics** [comment]
yep the pararead isssue is fixed. now gotta deal with the next package not installing, fst-pso... thanks though :)
