### ISSUE TITLE
bam2bed_shift.pl functionality

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#32]
Not an issue - just a question.

The reads / bed entries that result from the bam2bed_shift.pl program are all 50 bp long. This is because of the lines:

`$start_extl = $start + 4 - 25;`
`$start_extr = $start + 4 + 25;`
`$end_extl = $end - 5 - 25;`
`$end_extr = $end - 5 + 25;`

which takes the start (or end) of the fragment, shifts it by 4 (or 5) and makes that position the center a 50 bp read. The same thing is done for the end of the fragment.

For example, a 78 bp fragment from chr1 that starts at 10353 and ends at 10431 will give the following output in the bed file:
`chr1    10332   10382   J00118:292:HKF77BBXX:4:1224:7933:31523  78      +`
`chr1    10401   10451   J00118:292:HKF77BBXX:4:1224:7933:31523  78      +`

My questions:
1) Why is the insertion site set as the center of a new 50 bp read? I would have assumed that the exact insertion sites would be the first and last bases of the new fragment.
2) Why a 50 bp read? Why not a 1 bp read representing the exact insertion site?

**Comment by jpsmith5** [comment]
The pipeline now does everything that used to be split up between  ```bam2bed_shift.pl, bedtools genomecov, norm_bedGraph.pl, bedGraphToBigWig``` and `bamSitesToWig` using only` bamSitesToWig`.

**Comment by nsheff** [comment]
`bamSitesToWig` is awesome!
