### ISSUE TITLE
pyTSSenrichment.py not handling interrupt signals properly

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#34]
I've updated pypiper to 0.7.0, pararead to 0.3.0 and the ATACseq pipeline to 0.6.1 (looper is at 0.6.0).
The good news is that (miraculously) the problems I was having with the pipeline randomly hanging at the pyTSSenrichment or fragLdistribution steps are no longer happening. Not sure why, but it definitely seems fixed.

Onto the bad news - I dont think that pyTSSenrichment is handling SIGTERM properly still. I've only got one instance so far but I'm attaching the logs here. This was run in `--recover` mode from the start. I haven't restarted this job yet.

I'm asking around here to see if anyone else has re-written this script to see if we can swap it out.

[ATACseq_log.md.txt](https://github.com/databio/ATACseq/files/1572380/ATACseq_log.md.txt)
[SU484-Blast-A-Syros_ATACseq.log.txt](https://github.com/databio/ATACseq/files/1572381/SU484-Blast-A-Syros_ATACseq.log.txt)

**Comment by nsheff** [comment]
Hi @rcorces have you ever encountered this issue since? Given that this is almost 4 years old I am wondering if it still needs to be investigated, or if we think it was a one-off strange issue

**Comment by rcorces** [comment]
I think this can be closed as a one-off. We definitely havent encountered this behavior on the UCSF cluster but we dont have job preemption here.
