### ISSUE TITLE
occasional chrM reads

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#41]
This happened a long time ago and I'm sure I could dig into it a bit more for you guys.

We observed a small number of chrM reads in our final aligned BAMs. It seems like some reads are slipping through the pre-alignments. I dont think there is an explicit removal of reads mapping to chrM (ie grep -v chrM) because this would be hard coded.

Have you guys ever seen this on your end?

**Comment by jpsmith5** [comment]
As a final follow up, just re-ran the mitoReads files. They aligned to rCRSd...Now on bowtie2 2.2.9, So maybe an older bowtie2 issue as we suspected that is now resolved. Closing.
