### ISSUE TITLE
Pipeline does not catch improperly paired fastq files

### ISSUE THREAD

**Issue by rcorces** [databio/pepatac#42]
Not sure if you guys care about this one. I downloaded some data from SRA that had improperly paired fastq files (R1 and R2 not the same length and the reads didnt match up). The pipeline does not protect against this and ran through to completion.

If you dont care, feel free to close. Just posting to bring it up. I know its an edge case.

**Comment by jpsmith5** [comment]
For now, would suggest we keep the checks out of the pipeline. If a user runs in to this issue, they can [track down the fastq_repair tools](https://github.com/linsalrob/fastq-pair) that exist for this purpose.
