### ISSUE TITLE
samblaster

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#57]
we should look into using [samblaster](https://github.com/GregoryFaust/samblaster) instead of PICARD for duplicate removal. I have heard it is faster and more convenient to use.

**Comment by jpsmith5** [comment]
This option exists in current dev branch.  In minimal testing, it clearly saves time, but haven't done thorough comparison.

**Comment by jpsmith5** [comment]
Made samblaster the default. It is both faster and uses less memory.

**Comment by nsheff** [comment]
make sure you update:
1. docs (prereqs)
2. container
