### ISSUE TITLE
zcat on macos

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#69]
pepatac is not running well on macos due to several zcats.

See here: https://github.com/databio/pypiper/issues/92

we should eliminate these.

can you think of another way to do this: https://github.com/databio/pepatac/blob/c2716246c5160c1ea0ea888c1797bc5741e546c7/tools/PEPATAC_annotation.R#L184

**Comment by jpsmith5** [comment]
Ah yes, I'll look at the R tool.  Zcat internal to the primary pipeline is fixed with 45c8f47.

**Comment by jpsmith5** [comment]
Addressed with 36ce0a5
