### ISSUE TITLE
Missing TSS instructions

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#70]
I can't find any documentation on TSS enrichments.

**Comment by jpsmith5** [comment]
There are descriptions of the files on the [glossary page](http://code.databio.org/PEPATAC/glossary/).  Do you mean a separate page about generating these independently?

**Comment by nsheff** [comment]
The reference genome has to have a TSS annotation, right? Or did you build those into the repo now?

I mean, how can someone get pepatac to generate TSS enrichment plots.

**Comment by jpsmith5** [comment]
Present now in the [FAQ](http://code.databio.org/PEPATAC/faq/) and as part of both the [basic install](http://code.databio.org/PEPATAC/install/#22-download-or-create-annotation-files) and [extended tutorial](http://code.databio.org/PEPATAC/tutorial/#22-download-or-create-annotation-files).
