### ISSUE TITLE
R function for BiocProject

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#73]
We need to create an R function that will read the PEP of a processed PEPATAC project and then load in the data (peak files, maybe) using [biocproject](https://github.com/pepkit/BiocProject)

this function will be useful to include with pepatac

**Comment by nsheff** [comment]
it should be possible to systematically find the files. @jpsmith5 can explain exactly the paths if you can't identify them from the pepatac script itself.

Also, I think this code should be put into the pepatac repository.

**Comment by michalstolarczyk** [comment]
Ok, I see that `{peak_calling_hg19}` *could* be inferred from 

PEP config:
```yaml
implied_columns:
  organism:
    human:
      genome: hg19
```

and this line:

https://github.com/databio/pepatac/blob/c2716246c5160c1ea0ea888c1797bc5741e546c7/pipelines/pepatac.py#L950-L951

But it seems like the `genome_assembly` is taken from the `argparse.Namespace` and not from the PEP config.

Unfortunately, I wasn't able to find the `{results_pipeline}` neither in `looper` nor in `PEPATAC`

**Comment by jpsmith5** [comment]
@michalstolarczyk I *think* the results_pipeline path is accessible in the `prj.metadata.results_subdir`? Let me look into this.

**Comment by michalstolarczyk** [comment]
That's right, but if it's not provided in the PEP config, it has `results_pipeline` value and I wasn't sure where it came from. 

It looks like the definition actually lives in `peppy`:

https://github.com/pepkit/peppy/blob/35da352ed44b1ee7551aa1c89d36111ac44b8ec3/peppy/project.py#L813-L817

**Comment by jpsmith5** [comment]
Function exists for now. Will reopen in future if changes necessary.
