### ISSUE TITLE
add summarize dependencies to container

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#74]
Due to https://github.com/pepkit/looper/issues/31 -- I think we can start by at least adding all summarizer deps into the main container. then at least the same container could be use for `summarize`.

It shouldn't be too hard to just add those deps in, right?

**Comment by jpsmith5** [comment]
So running `looper summarize` using the container? Therefore the container must 'contain' all the required components for the summarizer script? This is the issue yes? It shouldn't be too hard to that into the container itself.

**Comment by jpsmith5** [comment]
@nsheff Thought: Does `Looper summarize` "know" how to submit the commands as a job? I think `summarize` is unaware of things like `--compute` and therefore doesn't know how to use a container... Therefore, if you don't have the requirements locally, it won't be able to execute the summarizer scripts.  In my test case, I do not have R installed locally, but I have the container and I have the pipeline and I get an:

```
/usr/bin/env: ‘Rscript’: No such file or directory
```

**Comment by jpsmith5** [comment]
Follow up: For example, the summarizer_subparser does not have a `--compute` or a `--env` option as it stands. So yeah, there would be no way it would understand how to submit the command in a container yes?  But, I'm not sure yet what the additional changes are in the class to take advantage of those options...

**Comment by nsheff** [comment]
> Does Looper summarize "know" how to submit the commands as a job?

The answer is No, that's what https://github.com/pepkit/looper/issues/31 is all about. What you're describing here is *exactly* that issue.

What I'm saying in this issue is this:

>  I think we can start by at least adding all summarizer deps into the main container. then at least the same container could be use for summarize

Then, someone could run `looper summarize` within the container as a workaround, until we solve that issue. This is what @armonazizi was doing in https://github.com/pepkit/looper/issues/48

But it can't work until we solve this issue.

**Comment by jpsmith5** [comment]
Gotcha! Okay, well the container is updated then and in all the places.
