### ISSUE TITLE
tutorial example question

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#76]
the tutorial example results are kind of strange because it's only one sample:

http://code.databio.org/PEPATAC/files/examples/tutorial/tutorial_summary.html

maybe we should make the tutorial use more than 1? or not show the looper summarize results?

**Comment by jpsmith5** [comment]
Yeah that's a good point @nsheff . I do have the "gold" project as the example for a multi-sample run.  I could potentially just add an additional emphasis in the tutorial to see that as another example of the output?  And/or I could also simply add a second sample.  I like having the looper summarize results included to really show the full potential of integrating all the components, so I'd prefer to keep it included.  Do you think adding a sample to the tutorial process is more helpful than just pointing them to the "gold" project example?

**Comment by jpsmith5** [comment]
Done
