### ISSUE TITLE
Error when running "pipelines/pepatac.py"

### ISSUE THREAD

**Issue by hiroyukikato911** [databio/pepatac#77]
Hi,

When I run "pipelines/pepatac.py" using prepared example file with the only exception using hg19, I get the following error.

<pre>
</pre>
Process 31497 returned: (0). Elapsed: 0:00:00. Peak memory: (Process: 0.0GB; Pipeline: 0.0GB)
Follow:
['/Users/hiroyukikato/pepatac_test/test1/raw/test1_R1.fastq.gz', '/Users/hiroyukikato/pepatac_test/test1/raw/test1_R2.fastq.gz']
['/Users/hiroyukikato/pepatac_test/test1/fastq/test1_R1.fastq', '/Users/hiroyukikato/pepatac_test/test1/fastq/test1_R2.fastq']
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1411, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 556, in main
    container=pm.container)
  File "/Users/hiroyukikato/Library/Python/2.7/lib/python/site-packages/pypiper/manager.py", line 722, in run
    call_follow()
  File "/Users/hiroyukikato/Library/Python/2.7/lib/python/site-packages/pypiper/manager.py", line 646, in call_follow
    follow()
  File "/Users/hiroyukikato/Library/Python/2.7/lib/python/site-packages/pypiper/ngstk.py", line 490, in temp_func
    for input_file in input_files])
  File "/Users/hiroyukikato/Library/Python/2.7/lib/python/site-packages/pypiper/ngstk.py", line 859, in count_reads
    return int(num_lines) / divisor
ValueError: invalid literal for int() with base 10: ''
Pipeline status: running

### Pipeline failed at:  (01-23 08:37:59) elapsed: 0.0 _TIME_

My code is
pipelines/pepatac.py 
--single-or-paired paired   
--prealignments rCRSd human_repeats  
 --genome hg19  
--sample-name test1   
--input examples/data/test1_r1.fastq.gz   
--input2 examples/data/test1_r2.fastq.gz   
--genome-size hs   
-O $HOME/pepatac_test

Is there anything to solve this problem?
Thank you so much in advance.

**Comment by jpsmith5** [comment]
Hi @hiroyukikato911,

I'm trying to replicate your error and so far I am not able to produce it.  I successfully ran your exact command.

A few things to check:
- First, just confirm that the test1_r1.fastq.gz files are not empty files (i.e. not file size 0).
- The error sounds like a problem with either the number of reads in the files producing an empty string or a floating point number that's being incorrectly cast as an int.  In the second case it could mean an update to `pypiper` would be helpful to produce a more meaningful error message.
- If you look in the PEPATAC_log.md file again for me, look for the phrase "reads lost" and confirm there's a 0 preceding it.

**Comment by nsheff** [comment]
@hiroyukikato911 it might be easier if you can attach your log file here.

@jpsmith5 when we figure out what is triggering this error, we should update the error message to be more informative

**Comment by jpsmith5** [comment]
Yes, agree to both statements.

**Comment by hiroyukikato911** [comment]
Hi,

Thank you so much for prompt response.
Followings are my situations.
・The test1_r1(and2).fastq.gz files are not empty(626 kb and 637kb each), but producing the next file "lock.fastq__tutorial_R1.fastq" which is 0 bite.
・It seems there is no phrase "reads lost" in my PEPATAC_log.md file.

Attached, please find my PEPATAC_log.md file.
[PEPATAC_log.md.zip](https://github.com/databio/pepatac/files/2790148/PEPATAC_log.md.zip)

Thank you so much for your kind support!
Best regards,

**Comment by nsheff** [comment]
This is due to a bug in pypiper with mac `wc`. We have fix now here: https://github.com/databio/pypiper/pull/115

**Comment by jpsmith5** [comment]
Additional findings:

- If running the pipeline using Docker, read over the notes in the [how to run PEPATAC in a container](http://code.databio.org/PEPATAC/howto/use-container/) help page, and importantly, remember to provide docker sufficient memory in the settings.  Specifically, try setting the Docker preference to maximum (CPU, memory, and swap).
- The source of the error remains unclear, but in a MacOS environment running Docker, there has been a reported error with the BAM file becoming corrupted during deduplication.  This can present as a samtools-based `EOF marker is absent. The input is probably truncated` error message. An alternative to using the default depuplication tool is simply to try out `Picard` instead using the `--deduplicator picard` option passed to the pipeline.  This has resolved the error in the reported instance.
- Finally, the error message `cannot execute binary file` likely reflects the presence of the incorrect operating system file for either or all of the following tools used by the pipeline: `skewer`, `bedGraphToBigWig`, `bedToBigBed`, `bigWigCat`, and `wigToBigWig`.  Be sure to download the appropriate Linux or MacOS based version of those tools depending on your host system.

**Comment by qiaowei-vvjoe** [comment]
Hi
@hiroyukikato911 Have you fixed your problem now?I think maybe I have the same error as you:

$ ~/configure/python3/bin/python3.6 pepatac.py --help
Traceback (most recent call last):
  File "pepatac.py", line 1422, in <module>
    sys.exit(main())
  File "pepatac.py", line 461, in main
    args = parse_arguments()
  File "pepatac.py", line 36, in parse_arguments
    required=["input", "genome", "sample-name", "output-parent"])
  File "/mnt/disk1/qiaowei/configure/python3/lib/python3.6/site-packages/pypiper/utils.py", line 60, in add_pypiper_args
    argument_groups=groups, arguments=args, use_all_args=all_args)
  File "/mnt/disk1/qiaowei/configure/python3/lib/python3.6/site-packages/pypiper/utils.py", line 808, in _determine_args
    from logmuse import LOGGING_CLI_OPTDATA
ImportError: cannot import name 'LOGGING_CLI_OPTDATA'

I tried several methods but still failed.
@jpsmith5 Could you please give me some advice to fix the error?Thank you so much in advance.

**Comment by nsheff** [comment]
are you using pypiper version 0.12.1?
If not I think try upgrading pypiper:

```
pip install --upgrade piper 
```

**Comment by qiaowei-vvjoe** [comment]
@nsheff 
yes.After I upgraded piper it succeed.
But when I try to test the sample use the following code something wrong with the attachment of PEPATAC_log.md. 
~/configure/python3/bin/python3.6 pipelines/pepatac.py
--single-or-paired paired
--prealignments rCRSd human_repeats
--genome hg38
--sample-name test1
--input examples/data/rawdata/test1_r1.fastq.gz
--input2 examples/data/rawdata/test1_r2.fastq.gz
--genome-size hs
-O examples/data/pepatac_test
[PEPATAC_log.md.zip](https://github.com/databio/pepatac/files/3638342/PEPATAC_log.md.zip)
it means that I must creat reference index hg38 like alignment steps as usual?But I have checked the indexed_bowtie2 it had indexed. or the PATH's question?Thank you so much for any help.
[qiaowei@clust1 indexed_bowtie2]$ l
total 3.9G
-rw-r--r--. 1 qiaowei qiaowei    0 Mar  7  2017 completed.flag
-rw-r--r--. 1 qiaowei qiaowei 938M Mar  7  2017 hg38.rev.1.bt2
-rw-r--r--. 1 qiaowei qiaowei 700M Mar  7  2017 hg38.rev.2.bt2
-rw-r--r--. 1 qiaowei qiaowei 938M Mar  7  2017 hg38.1.bt2
-rw-r--r--. 1 qiaowei qiaowei 700M Mar  7  2017 hg38.2.bt2
-rw-r--r--. 1 qiaowei qiaowei  11K Mar  7  2017 hg38.3.bt2
-rw-r--r--. 1 qiaowei qiaowei 700M Mar  7  2017 hg38.4.bt2
lrwxrwxrwx. 1 qiaowei qiaowei   10 Mar  7  2017 hg38.fa -> ../hg38.fa

**Comment by qiaowei-vvjoe** [comment]
@jpsmith5 @nsheff 
I also read https://github.com/databio/pepatac/issues/50 and checked GENOMES="/mnt/disk1/qiaowei/pepatac_tutorial/genomes/" in .bashrc.
I don't know why it cannot find the 'hg38' index at: ${GENOMES}/hg38/indexed_bowtie2.
Besides, in issues50 what is the --bind means I can't find it in PEPENV docs.
I haven't use singularity but download software one by one.
Thank you so much in advance.
