### ISSUE TITLE
repository size

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#82]
I'm cloning the pepatac repository and it's very large... more than 100 Mb and still not finished, and is taking several minutes on my not-super-fast home connection. We should probably rethink what we're putting in this repository....

It looks like the big culprits are these files:

27M	examples/data/tutorial_r1.fastq.gz
28M	examples/data/tutorial_r2.fastq.gz

I don't think it's acceptable to put such large binary files into a git repository -- especially just for a tutorial. these should be put into big.databio.org and then instructions for downloading them in the tutorial. to remove them from the repository it will not be enough to simply delete them, because they will be retained in the history. It will be necessary to purge them from the history, which is not ideal, but a necessary evil in this case.

While going to this effort we may want to rethink the files in the `anno` folder as well. they are smaller and maybe that's borderline, since they're actually used by the pipeline...

**Comment by nsheff** [comment]
@jpsmith is this solved?

**Comment by jpsmith5** [comment]
Resolved.  Moved tutorial and annotation files to [big.databio.org](http://big.databio.org)
