### ISSUE TITLE
MACS2 parameters customized in yaml 

### ISSUE THREAD

**Issue by shmilyfhh** [databio/pepatac#87]
Hi there,

I am struggling with the MACS2 parameters in the yaml file. Briefly, I would like to try out the combination described in the SCIENCE paper (The chromatin accessibility landscape of primary human cancers), "For each sample, peak calling was performed on the Tn5- corrected single-base insertions using the MACS2 callpeak command with parameters “--shift -75 --extsize 150 --nomodel --call-summits --nolambda --keep-dup all -p 0.01”. The peak summits were then extended by 250 bp on either side to a final width of 501 bp,". I followed the yaml format, but it looks like it does take some of the parameters like "shift" and "nomodel". The rest of the parameters are ignored as I check the running log. "p" or "pvalue" can't be recognized. 

Also, I would like to know how far this pipeline goes, regarding the paper's peak filtering process (i.e. blacklist filter, chromosome length restriction, and peak overlapping issue) right after the peak calling?

Thanks,
Huihui

**Comment by jpsmith5** [comment]
Thanks for bringing this to our attention Huihui.  We are actively correcting this and should have a solution in the next day or so.  As a temporary fix while we test and roll out the changes, you can edit the `MACS2` call directly in `pepatac.py`.

On line 1165 of `pepatac.py` (or search for the phrase "macs_cmd_chunks"), you can find the formatting of the `MACS2` call and associated parameters.

This is the current appearance:
```
macs_cmd_chunks = [
    "{} callpeak".format(tools.macs2),
    ("-t", peak_input_file),
    "-f BED",
    ("-g", args.genome_size),
    ("--outdir", peak_folder),
    ("-n", args.sample_name),
    ("-q", param.macs2.q),
    ("--shift", param.macs2.shift),
    "--nomodel"
]
```
 What you can change that to for the moment is the following:
```
macs_cmd_chunks = [
    "{} callpeak".format(tools.macs2),
    ("-t", peak_input_file),
    "-f BED",
    ("-g", args.genome_size),
    ("--outdir", peak_folder),
    ("-n", args.sample_name),
    "--shift -75 --extsize 150 --nomodel --call-summits --nolambda --keep-dup all -p 0.01"
]
```

Blacklist filtering is dependent on whether there is a blacklist file present in the genome folder which I now realize is not well documented and will update accordingly.  However, if for example you're using `hg38`, in the `hg38/` `GENOMES` folder, you would place a `hg38.blacklist.bed` file that  follows standard BED format and includes your regions to be blacklisted. [Here is the blacklist file used in the paper](http://big.databio.org/pepatac/hg38.blacklist.bed).  Just be sure to move it to the `hg38/` genomes folder.  

For the chromosome length restriction, we do not have that as an included step, as in the paper the peaks are extended *after* `MACS2`, thereby introducing the potential for extending beyond chromosome boundaries independent of `MACS2`'s calls. 

The overlapping peak problem is then also a consequence of that manual extension procedure. Both of those procedures are more user/project dependent and for, at least the moment, not universal analyses to the degree we include them as default processes in the pipeline.

**Comment by shmilyfhh** [comment]
Thank you so much for the helpful information. It makes sense to go as far as the peak calling. By the way, it is a nicely organized pipeline!

**Comment by jpsmith5** [comment]
Updated how tools are parameterized.  See 4ce8666 and a4bf65d.

**Comment by nsheff** [comment]
@shmilyfhh you should be able to paramaterize in the `yaml` file now using the latest release of pepatac.
