### ISSUE TITLE
samtools given bad options

### ISSUE THREAD

**Issue by caldodge** [databio/pepatac#95]
[PEPATAC_log.md.txt](https://github.com/databio/pepatac/files/3128494/PEPATAC_log.md.txt)

PEPATAC appears to be passing invalid options to samtools 1.8.  Is this because some option is not being used?  -@ does not appear in the samtools man page.

**Comment by nsheff** [comment]
Can you confirm that you're using a recent version of `samtools` ? With Samtools 1.9, these are valid options.

```samtools --version

samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```

**Comment by nsheff** [comment]
I also confirmed that this works with `samtools 1.7`. I'm guessing you're using samtools 0.X...

```
samtools view b6_f7_temp.bam -@ 3 | head
HWI-ST558:621:HY2VFBCX2:2:2102:15223:22839      16      chr1    3000321 27      56M     *       0       0       GTTGTTATGTCTCCTTTTTCATTTCTGATTTTGTTAATTATAGTACAGTCCCTATG   FHHHHH@F1@<?E=FHHHHHHF@HHHHHFC11@@HEHD1H@CGC<@CD11GD@DD<        AS:i:-5 XS:i:-33        XN:i:0     XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:4G51       YT:Z:UU RG:Z:b6_f7
HWI-ST558:621:HY2VFBCX2:2:1108:18280:12289      16      chr1    3000762 30      71M     *       0       0       GTTCAGTTTCCAGGTGAATGTTGGCTTTCTATTATTTATGCTGTTATTGAAGATCAGCCTTAGTCCGTAGT    IIIIHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIDDDDD AS:i:0     XS:i:-6 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:71 YT:Z:UU RG:Z:b6_f7
HWI-ST558:621:HY2VFBCX2:2:2210:11642:64552      16      chr1    3000762 30      71M     *       0       0       GTTCAGTTTCCAGGTGAATGTTGGCTTTCTATTATTTATGCTGTTATTGAAGATCAGCCTTAGTCCGTAGT    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIHIIIIHHHHHIIHIIIIHDHGIH@BD@D AS:i:0     XS:i:-6 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:71 YT:Z:UU RG:Z:b6_f7
samtools --version
samtools 1.7
Using htslib 1.7

```

**Comment by nsheff** [comment]
it is true that there's probably no point in using the `-@` option for `view` though, I'm not sure what that would do...

**Comment by caldodge** [comment]
Using samtools 1.8. "-@" does not appear in the man page.  Any chance this
is activated by a specific samtools build option?  At any rate, we'll build
and install samtools 1.9 to see if that fixes the issue.

**Comment by nsheff** [comment]
The `@` option appears on the samtools man page since version 1.2:  http://www.htslib.org/doc/samtools-1.2.html

It's also on the man page for 1.8: http://www.htslib.org/doc/samtools-1.8.html

I don't think it's a special build option; I'm guessing you've been using samtools 0 even though you think you're using 1.8. can you show the output of `samtools --version` ?

**Comment by caldodge** [comment]
[dodgec@csclprd3 ~]$ module load samtools
[dodgec@csclprd3 ~]$ samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.

**Comment by nsheff** [comment]
did switching to 1.9 solve your issue?

**Comment by caldodge** [comment]
Nathan,

Yes, thanks - version 1.9 worked fine.
