### ISSUE TITLE
bug in gzipping

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#96]
https://github.com/databio/pepatac/blob/1c237cd155480d3aeb0a1fcf23361e169561cf2b/pipelines/pepatac.py#L783-L788

THis is producing this: 
```
### Map to genome (04-29 14:45:55) elapsed: 0.0 _TIME_

Target exists: `/sfs/lustre/allocations/shefflab/processed/dura_macs/results_pipeline/b6_f7/aligned_mm10/b6_f7_sort.bam`
Target to produce: `.gz`


> `pigz -f -p 8 ` (3186)
```

which has no files (there's a space there)...

**Comment by nsheff** [comment]
looks like it's just a problem with single-end data.

**Comment by jpsmith5** [comment]
This should be resolved. Closing for now.
