### ISSUE TITLE
bamsitestoWig

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#97]
We could convert perl scripts into C, and then package this up and distribute via pypi.

**Comment by jpsmith5** [comment]
This is moved over to https://github.com/databio/smugwig and it's still in the works.  Multiple issues keep cropping up.

**Comment by nsheff** [comment]
what is your plan for smugwig?

**Comment by jpsmith5** [comment]
I would like to get it working, but the last time I put a big push in for each problem solved, I would uncover a new one. If I recall, mostly with things getting out of sync.
