### ISSUE TITLE
hg19_TSS.tgz is empty

### ISSUE THREAD

**Issue by sthair** [databio/pepatac#98]
Hi there, 
Please see attached log..

I was able to run this exact same process successfully with ```--genome hg38```

Now with ```--genome hg19``` it fails. I was able to run this sample through with hg19 on the Chang lab server so I know the sample is just fine. And in fact the insert size distribution plots look very similar. 

I think (?) this is because the hg19_TSS.tgz file at http://big.databio.org/refgenomes/
is empty. 

I've reloaded and unpacked twice just to check. 
```wget http://big.databio.org/refgenomes/hg19_TSS.tgz
tar xvzf hg19_TSS.tgz
ls -lh
 194 Mar 15 07:50 hg19_TSS.tgz
 45 Mar 15 07:49 hg19_TSS.tsv ```
[PEPATAC_log.txt](https://github.com/databio/pepatac/files/3129687/PEPATAC_log.txt)


Can you help? 

Cheers
Simone

**Comment by nsheff** [comment]
you're right, that file is incorrect! I will replace it tomorrow. sorry about that.

**Comment by nsheff** [comment]
Alright here you go: http://big.databio.org/refgenomes/hg19_TSS.tsv.gz

**Comment by sthair** [comment]
Thank you!
